// Dados Ordem Paranormal RPG
const PERICIAS = [
  { id: 'acrobacia', nome: 'Acrobacia+', attr: 'AGI', onlyTrained: false, loadPenalty: true },
  { id: 'adestramento', nome: 'Adestramento*', attr: 'PRE', onlyTrained: true, loadPenalty: false },
  { id: 'artes', nome: 'Artes*', attr: 'PRE', onlyTrained: true, loadPenalty: false },
  { id: 'atletismo', nome: 'Atletismo', attr: 'FOR', onlyTrained: false, loadPenalty: true },
  { id: 'atualidades', nome: 'Atualidades', attr: 'INT', onlyTrained: false, loadPenalty: false },
  { id: 'ciencias', nome: 'Ciencias*', attr: 'INT', onlyTrained: true, loadPenalty: false },
  { id: 'crime', nome: 'Crime*+', attr: 'AGI', onlyTrained: true, loadPenalty: true },
  { id: 'diplomacia', nome: 'Diplomacia', attr: 'PRE', onlyTrained: false, loadPenalty: false },
  { id: 'enganacao', nome: 'Enganacao', attr: 'PRE', onlyTrained: false, loadPenalty: false },
  { id: 'fortitude', nome: 'Fortitude', attr: 'VIG', onlyTrained: false, loadPenalty: false },
  { id: 'furtividade', nome: 'Furtividade+', attr: 'AGI', onlyTrained: false, loadPenalty: true },
  { id: 'iniciativa', nome: 'Iniciativa', attr: 'AGI', onlyTrained: false, loadPenalty: false },
  { id: 'intimidacao', nome: 'Intimidacao', attr: 'PRE', onlyTrained: false, loadPenalty: false },
  { id: 'intuicao', nome: 'Intuicao', attr: 'PRE', onlyTrained: false, loadPenalty: false },
  { id: 'investigacao', nome: 'Investigacao', attr: 'INT', onlyTrained: false, loadPenalty: false },
  { id: 'luta', nome: 'Luta', attr: 'FOR', onlyTrained: false, loadPenalty: false },
  { id: 'medicina', nome: 'Medicina', attr: 'INT', onlyTrained: false, loadPenalty: false },
  { id: 'ocultismo', nome: 'Ocultismo*', attr: 'INT', onlyTrained: true, loadPenalty: false },
  { id: 'percepcao', nome: 'Percepcao', attr: 'PRE', onlyTrained: false, loadPenalty: false },
  { id: 'pilotagem', nome: 'Pilotagem*', attr: 'AGI', onlyTrained: false, loadPenalty: false },
  { id: 'pontaria', nome: 'Pontaria', attr: 'AGI', onlyTrained: false, loadPenalty: false },
  { id: 'profissao', nome: 'Profissao*', attr: 'INT', onlyTrained: true, loadPenalty: false },
  { id: 'reflexos', nome: 'Reflexos', attr: 'AGI', onlyTrained: false, loadPenalty: false },
  { id: 'religiao', nome: 'Religiao*', attr: 'PRE', onlyTrained: true, loadPenalty: false },
  { id: 'sobrevivencia', nome: 'Sobrevivencia', attr: 'INT', onlyTrained: false, loadPenalty: false },
  { id: 'tatica', nome: 'Tatica*', attr: 'INT', onlyTrained: true, loadPenalty: false },
  { id: 'tecnologia', nome: 'Tecnologia*', attr: 'INT', onlyTrained: true, loadPenalty: false },
  { id: 'vontade', nome: 'Vontade', attr: 'PRE', onlyTrained: false, loadPenalty: false },
];
const ORIGENS = {
  academico: { nome: 'Academico', pericias: ['ciencias', 'investigacao'], poder: 'Saber e Poder' },
  investigador: { nome: 'Investigador', pericias: ['investigacao', 'percepcao'], poder: 'Faro para Pistas' },
  policial: { nome: 'Policial', pericias: ['percepcao', 'pontaria'], poder: 'Patrulha' },
  religioso: { nome: 'Religioso', pericias: ['religiao', 'vontade'], poder: 'Calma Interior' },
  cultista: { nome: 'Cultista Arrependido', pericias: ['ocultismo', 'religiao'], poder: 'Tracos do Outro Lado' },
  soldado: { nome: 'Soldado', pericias: ['luta', 'fortitude'], poder: 'Posicao de Combate' },
  ti: { nome: 'T.I.', pericias: ['investigacao', 'tecnologia'], poder: 'Motor de Busca' },
  criminoso: { nome: 'Criminoso', pericias: ['crime', 'furtividade'], poder: 'O Crime Compensa' },
  artista: { nome: 'Artista', pericias: ['artes', 'enganacao'], poder: 'Magnum Opus' },
  atleta: { nome: 'Atleta', pericias: ['acrobacia', 'atletismo'], poder: '110%' },
  universitario: { nome: 'Universitario', pericias: ['atualidades', 'investigacao'], poder: 'Estudante Aplicado' },
  mercenario: { nome: 'Mercenario', pericias: ['iniciativa', 'intimidacao'], poder: 'Posicao de Combate' },
  militar: { nome: 'Militar', pericias: ['pontaria', 'tatica'], poder: 'Para Bellum' },
  trambiqueiro: { nome: 'Trambiqueiro', pericias: ['crime', 'enganacao'], poder: 'Impostor' },
  lutador: { nome: 'Lutador', pericias: ['luta', 'reflexos'], poder: 'Brecha' },
  teorico: { nome: 'Teorico da Conspiracao', pericias: ['investigacao', 'ocultismo'], poder: 'Eu Ja Sabia' },
};
const CLASSES = {
  combatente: { nome: 'Combatente', pvBase: 20, pvPorNex: 4, sanBase: 12, sanPorNex: 3, peBase: 2, pePorNex: 2, periciasBase: 1, proficiencias: 'Armas simples e taticas, Protecoes leves e medias', habilidadesIniciais: ['Ataque Especial', 'Treinamento em Luta ou Pontaria'] },
  especialista: { nome: 'Especialista', pvBase: 16, pvPorNex: 3, sanBase: 16, sanPorNex: 4, peBase: 3, pePorNex: 3, periciasBase: 3, proficiencias: 'Armas simples, Protecoes leves', habilidadesIniciais: ['Ecletico', 'Perito'] },
  ocultista: { nome: 'Ocultista', pvBase: 12, pvPorNex: 2, sanBase: 20, sanPorNex: 5, peBase: 4, pePorNex: 4, periciasBase: 1, proficiencias: 'Armas simples', habilidadesIniciais: ['Escolhido pelo Outro Lado', 'Impostor'] },
};
// RITUAIS_CATALOG esta em rituais-catalog.js
const ARMAS_PRESET = [
  { nome: 'Punho', dano: '1d3', critico: 20, multiplicador: 2, tipoDano: 'Contundente', alcance: '-', pericia: 'Luta', atributoDano: 'Força', bonusAtaque: 0 },
  { nome: 'Faca', dano: '1d4', critico: 19, multiplicador: 2, tipoDano: 'Cortante', alcance: '-', pericia: 'Luta', atributoDano: 'Força', bonusAtaque: 0 },
  { nome: 'Pistola', dano: '1d12', critico: 18, multiplicador: 2, tipoDano: 'Balístico', alcance: 'Curto', pericia: 'Pontaria', atributoDano: 'Agilidade', bonusAtaque: 0 },
  { nome: 'Revólver', dano: '2d6', critico: 19, multiplicador: 3, tipoDano: 'Balístico', alcance: 'Curto', pericia: 'Pontaria', atributoDano: 'Agilidade', bonusAtaque: 0 },
  { nome: 'Fuzil de Assalto', dano: '2d10', critico: 19, multiplicador: 2, tipoDano: 'Balístico', alcance: 'Médio', pericia: 'Pontaria', atributoDano: 'Agilidade', bonusAtaque: 0 },
];
