// Dados oficiais de Ordem Paranormal RPG (1ª edição)

const PERICIAS = [
  { id: 'acrobacia', nome: 'Acrobacia+', attr: 'AGI', onlyTrained: false, loadPenalty: true },
  { id: 'adestramento', nome: 'Adestramento*', attr: 'PRE', onlyTrained: true, loadPenalty: false },
  { id: 'artes', nome: 'Artes*', attr: 'PRE', onlyTrained: true, loadPenalty: false },
  { id: 'atletismo', nome: 'Atletismo', attr: 'FOR', onlyTrained: false, loadPenalty: true },
  { id: 'atualidades', nome: 'Atualidades', attr: 'INT', onlyTrained: false, loadPenalty: false },
  { id: 'ciencias', nome: 'Ciências*', attr: 'INT', onlyTrained: true, loadPenalty: false },
  { id: 'crime', nome: 'Crime*+', attr: 'AGI', onlyTrained: true, loadPenalty: true },
  { id: 'diplomacia', nome: 'Diplomacia', attr: 'PRE', onlyTrained: false, loadPenalty: false },
  { id: 'enganacao', nome: 'Enganação', attr: 'PRE', onlyTrained: false, loadPenalty: false },
  { id: 'fortitude', nome: 'Fortitude', attr: 'VIG', onlyTrained: false, loadPenalty: false },
  { id: 'furtividade', nome: 'Furtividade+', attr: 'AGI', onlyTrained: false, loadPenalty: true },
  { id: 'iniciativa', nome: 'Iniciativa', attr: 'AGI', onlyTrained: false, loadPenalty: false },
  { id: 'intimidacao', nome: 'Intimidação', attr: 'PRE', onlyTrained: false, loadPenalty: false },
  { id: 'intuicao', nome: 'Intuição', attr: 'PRE', onlyTrained: false, loadPenalty: false },
  { id: 'investigacao', nome: 'Investigação', attr: 'INT', onlyTrained: false, loadPenalty: false },
  { id: 'luta', nome: 'Luta', attr: 'FOR', onlyTrained: false, loadPenalty: false },
  { id: 'medicina', nome: 'Medicina', attr: 'INT', onlyTrained: false, loadPenalty: false },
  { id: 'ocultismo', nome: 'Ocultismo*', attr: 'INT', onlyTrained: true, loadPenalty: false },
  { id: 'percepcao', nome: 'Percepção', attr: 'PRE', onlyTrained: false, loadPenalty: false },
  { id: 'pilotagem', nome: 'Pilotagem*', attr: 'AGI', onlyTrained: true, loadPenalty: false },
  { id: 'pontaria', nome: 'Pontaria', attr: 'AGI', onlyTrained: false, loadPenalty: false },
  { id: 'profissao', nome: 'Profissão*', attr: 'INT', onlyTrained: true, loadPenalty: false },
  { id: 'reflexos', nome: 'Reflexos', attr: 'AGI', onlyTrained: false, loadPenalty: false },
  { id: 'religiao', nome: 'Religião*', attr: 'PRE', onlyTrained: true, loadPenalty: false },
  { id: 'sobrevivencia', nome: 'Sobrevivência', attr: 'INT', onlyTrained: false, loadPenalty: false },
  { id: 'tatica', nome: 'Tática*', attr: 'INT', onlyTrained: true, loadPenalty: false },
  { id: 'tecnologia', nome: 'Tecnologia*', attr: 'INT', onlyTrained: true, loadPenalty: false },
  { id: 'vontade', nome: 'Vontade', attr: 'PRE', onlyTrained: false, loadPenalty: false },
];

const ITEM_CATEGORIES = ['0', 'I', 'II', 'III', 'IV'];
const ELEMENTOS = ['Sangue', 'Morte', 'Conhecimento', 'Energia', 'Medo', 'Outro'];

const ORIGENS = {
  academico: { nome: 'Acadêmico', pericias: ['ciencias', 'investigacao'], poder: 'Saber é Poder' },
  agente_saude: { nome: 'Agente de Saúde', pericias: ['intuicao', 'medicina'], poder: 'Técnica Medicinal' },
  amnesico: { nome: 'Amnésico', pericias: [], poder: 'Vislumbres do Passado' },
  artista: { nome: 'Artista', pericias: ['artes', 'enganacao'], poder: 'Magnum Opus' },
  atleta: { nome: 'Atleta', pericias: ['acrobacia', 'atletismo'], poder: '110%' },
  chef: { nome: 'Chef', pericias: ['fortitude', 'profissao'], poder: 'Ingrediente Secreto' },
  criminoso: { nome: 'Criminoso', pericias: ['crime', 'furtividade'], poder: 'O Crime Compensa' },
  cultista: { nome: 'Cultista Arrependido', pericias: ['ocultismo', 'religiao'], poder: 'Traços do Outro Lado' },
  desgarrado: { nome: 'Desgarrado', pericias: ['fortitude', 'sobrevivencia'], poder: 'Calejado' },
  engenheiro: { nome: 'Engenheiro', pericias: ['profissao', 'tecnologia'], poder: 'Ferramenta Favorita' },
  executivo: { nome: 'Executivo', pericias: ['diplomacia', 'profissao'], poder: 'Processo Otimizado' },
  investigador: { nome: 'Investigador', pericias: ['investigacao', 'percepcao'], poder: 'Faro para Pistas' },
  operario: { nome: 'Operário', pericias: ['fortitude', 'profissao'], poder: 'Ferramentas da Profissão' },
  policial: { nome: 'Policial', pericias: ['percepcao', 'pontaria'], poder: 'Patrulha' },
  religioso: { nome: 'Religioso', pericias: ['religiao', 'vontade'], poder: 'Calma Interior' },
  servidor: { nome: 'Servidor Público', pericias: ['diplomacia', 'intuicao'], poder: 'Processo Burocrático' },
  soldado: { nome: 'Soldado', pericias: ['luta', 'fortitude'], poder: 'Posição de Combate' },
  ti: { nome: 'T.I.', pericias: ['investigacao', 'tecnologia'], poder: 'Motor de Busca' },
  trabalhador: { nome: 'Trabalhador Rural', pericias: ['atletismo', 'sobrevivencia'], poder: 'Raízes' },
  universitario: { nome: 'Universitário', pericias: ['atualidades', 'investigacao'], poder: 'Estudante Aplicado' },
  mercenario: { nome: 'Mercenário', pericias: ['iniciativa', 'intimidacao'], poder: 'Posição de Combate' },
  militar: { nome: 'Militar', pericias: ['pontaria', 'tatica'], poder: 'Para Bellum' },
  trambiqueiro: { nome: 'Trambiqueiro', pericias: ['crime', 'enganacao'], poder: 'Impostor' },
  lutador: { nome: 'Lutador', pericias: ['luta', 'reflexos'], poder: 'Brecha' },
  teorico: { nome: 'Teórico da Conspiração', pericias: ['investigacao', 'ocultismo'], poder: 'Eu Já Sabia' },
};

const CLASSES = {
  combatente: {
    nome: 'Combatente', pvBase: 20, pvPorNex: 4, sanBase: 12, sanPorNex: 3, peBase: 2, pePorNex: 2,
    periciasBase: 1, proficiencias: 'Armas simples e táticas, Proteções leves e médias',
    habilidadesIniciais: ['Ataque Especial', 'Treinamento em Luta ou Pontaria'],
  },
  especialista: {
    nome: 'Especialista', pvBase: 16, pvPorNex: 3, sanBase: 16, sanPorNex: 4, peBase: 3, pePorNex: 3,
    periciasBase: 3, proficiencias: 'Armas simples, Proteções leves',
    habilidadesIniciais: ['Eclético', 'Perito'],
  },
  ocultista: {
    nome: 'Ocultista', pvBase: 12, pvPorNex: 2, sanBase: 20, sanPorNex: 5, peBase: 4, pePorNex: 4,
    periciasBase: 1, proficiencias: 'Armas simples',
    habilidadesIniciais: ['Escolhido pelo Outro Lado', 'Impostor'],
  },
};

function calcularPericiasMax(classe, int, origemPericiasCount = 2) {
  const base = CLASSES[classe]?.periciasBase ?? 1;
  return base + int + origemPericiasCount;
}

const RITUAIS_CATALOG = [
  { nome: 'Amaldiçoar Arma', circulo: '1º', elemento: 'Variável' },
  { nome: 'Compreensão Paranormal', circulo: '1º', elemento: 'Conhecimento' },
  { nome: 'Enfeitiçar', circulo: '1º', elemento: 'Conhecimento' },
  { nome: 'Perturbação', circulo: '1º', elemento: 'Conhecimento' },
  { nome: 'Ouvir os Sussurros', circulo: '1º', elemento: 'Conhecimento' },
  { nome: 'Tecer Ilusão', circulo: '1º', elemento: 'Energia' },
  { nome: 'Terceiro Olho', circulo: '1º', elemento: 'Conhecimento' },
  { nome: 'Amaldiçoar Tecnologia', circulo: '1º', elemento: 'Energia' },
  { nome: 'Coincidência Forçada', circulo: '1º', elemento: 'Energia' },
  { nome: 'Eletrocussão', circulo: '1º', elemento: 'Energia' },
  { nome: 'Embaralhar', circulo: '1º', elemento: 'Energia' },
  { nome: 'Luz', circulo: '1º', elemento: 'Energia' },
  { nome: 'Polarização Caótica', circulo: '1º', elemento: 'Energia' },
  { nome: 'Cicatrização', circulo: '1º', elemento: 'Sangue' },
  { nome: 'Consumir Manancial', circulo: '1º', elemento: 'Sangue' },
  { nome: 'Decadência', circulo: '1º', elemento: 'Morte' },
  { nome: 'Definhar', circulo: '1º', elemento: 'Morte' },
  { nome: 'Espirais da Perdição', circulo: '1º', elemento: 'Morte' },
  { nome: 'Nuvem de Cinzas', circulo: '1º', elemento: 'Morte' },
  { nome: 'Arma Atroz', circulo: '1º', elemento: 'Sangue' },
  { nome: 'Armadura de Sangue', circulo: '1º', elemento: 'Sangue' },
  { nome: 'Corpo Adaptado', circulo: '1º', elemento: 'Sangue' },
  { nome: 'Distorcer Aparência', circulo: '1º', elemento: 'Sangue' },
  { nome: 'Fortalecimento Sensorial', circulo: '1º', elemento: 'Sangue' },
  { nome: '\u00d3dio Incontrol\u00e1vel', circulo: '1º', elemento: 'Sangue' },
  { nome: 'Ciner\u00e1ria', circulo: '2º', elemento: 'Morte' },
  { nome: 'Aprimorar Mente', circulo: '2º', elemento: 'Conhecimento' },
  { nome: 'Detecção de Ameaças', circulo: '2º', elemento: 'Conhecimento' },
  { nome: 'Esconder dos Olhos', circulo: '2º', elemento: 'Conhecimento' },
  { nome: 'Invadir Mente', circulo: '2º', elemento: 'Conhecimento' },
  { nome: 'Localização', circulo: '2º', elemento: 'Conhecimento' },
  { nome: 'Chamas do Caos', circulo: '2º', elemento: 'Energia' },
  { nome: 'Contenção Fantasmagórica', circulo: '2º', elemento: 'Energia' },
  { nome: 'Dissonância Acústica', circulo: '2º', elemento: 'Energia' },
  { nome: 'Sopro do Caos', circulo: '2º', elemento: 'Energia' },
  { nome: 'Tela de Ruído', circulo: '2º', elemento: 'Energia' },
  { nome: 'Desacelerar Impacto', circulo: '2º', elemento: 'Morte' },
  { nome: 'Eco Espiral', circulo: '2º', elemento: 'Morte' },
  { nome: 'Paradoxo', circulo: '2º', elemento: 'Energia' },
  { nome: 'Miasma Entrópico', circulo: '2º', elemento: 'Morte' },
  { nome: 'Velocidade Mortal', circulo: '2º', elemento: 'Morte' },
  { nome: 'Aprimorar Físico', circulo: '2º', elemento: 'Sangue' },
  { nome: 'Descarnar', circulo: '2º', elemento: 'Sangue' },
  { nome: 'Flagelo de Sangue', circulo: '2º', elemento: 'Sangue' },
  { nome: 'Hemofagia', circulo: '2º', elemento: 'Sangue' },
  { nome: 'Transfusão Vital', circulo: '2º', elemento: 'Sangue' },
  { nome: 'Proteção contra Rituais', circulo: '2º', elemento: 'Conhecimento' },
  { nome: 'Rejeitar Névoa', circulo: '2º', elemento: 'Conhecimento' },
  { nome: 'Alterar Memória', circulo: '3º', elemento: 'Conhecimento' },
  { nome: 'Contato Paranormal', circulo: '3º', elemento: 'Conhecimento' },
  { nome: 'Mergulho Mental', circulo: '3º', elemento: 'Conhecimento' },
  { nome: 'Vidência', circulo: '3º', elemento: 'Conhecimento' },
  { nome: 'Convocação Instantânea', circulo: '3º', elemento: 'Energia' },
  { nome: 'Salto Fantasma', circulo: '3º', elemento: 'Energia' },
  { nome: 'Transfigurar Água', circulo: '3º', elemento: 'Energia' },
  { nome: 'Transfigurar Terra', circulo: '3º', elemento: 'Energia' },
  { nome: 'Âncora Temporal', circulo: '3º', elemento: 'Morte' },
  { nome: 'Barganha Insana', circulo: '3º', elemento: 'Medo' },
  { nome: 'Poeira da Podridão', circulo: '3º', elemento: 'Morte' },
  { nome: 'Tentáculos de Lodo', circulo: '3º', elemento: 'Morte' },
  { nome: 'Zerar Entropia', circulo: '3º', elemento: 'Morte' },
  { nome: 'Ferver Sangue', circulo: '3º', elemento: 'Sangue' },
  { nome: 'Forma Monstruosa', circulo: '3º', elemento: 'Sangue' },
  { nome: 'Purgatório', circulo: '3º', elemento: 'Sangue' },
  { nome: 'Vomitar Pestes', circulo: '3º', elemento: 'Sangue' },
  { nome: 'Dissipar Ritual', circulo: '4º', elemento: 'Conhecimento' },
  { nome: 'Controle Mental', circulo: '4º', elemento: 'Conhecimento' },
  { nome: 'Inexistir', circulo: '4º', elemento: 'Medo' },
  { nome: 'Possessão', circulo: '4º', elemento: 'Conhecimento' },
  { nome: 'Alterar Destino', circulo: '4º', elemento: 'Energia' },
  { nome: 'Deflagração de Energia', circulo: '4º', elemento: 'Energia' },
  { nome: 'Teletransporte', circulo: '4º', elemento: 'Energia' },
  { nome: 'Convocar o Algoz', circulo: '4º', elemento: 'Morte' },
  { nome: 'Distorção Temporal', circulo: '4º', elemento: 'Morte' },
  { nome: 'Fim Inevitável', circulo: '4º', elemento: 'Morte' },
  { nome: 'Capturar o Coração', circulo: '4º', elemento: 'Sangue' },
  { nome: 'Invólucro de Carne', circulo: '4º', elemento: 'Sangue' },
  { nome: 'Vínculo de Sangue', circulo: '4º', elemento: 'Sangue' },
  { nome: 'Canalizar o Medo', circulo: 'Especial', elemento: 'Medo' },
  { nome: 'Conhecendo o Medo', circulo: 'Especial', elemento: 'Medo' },
  { nome: 'Lâmina do Medo', circulo: 'Especial', elemento: 'Medo' },
  { nome: 'Medo Tangível', circulo: 'Especial', elemento: 'Medo' },
  { nome: 'Presença do Medo', circulo: 'Especial', elemento: 'Medo' },
];

const ARMAS_PRESET = [
  { nome: 'Punho', dano: '1d3', critico: 20, multiplicador: 2, tipoDano: 'Contundente', alcance: '—', pericia: 'Luta', atributoDano: 'Força', bonusAtaque: 0 },
  { nome: 'Faca', dano: '1d4', critico: 19, multiplicador: 2, tipoDano: 'Cortante', alcance: '—', pericia: 'Luta', atributoDano: 'Força', bonusAtaque: 0 },
  { nome: 'Bastão', dano: '1d6', critico: 20, multiplicador: 2, tipoDano: 'Contundente', alcance: '—', pericia: 'Luta', atributoDano: 'Força', bonusAtaque: 0 },
  { nome: 'Espada Curta', dano: '1d6', critico: 19, multiplicador: 2, tipoDano: 'Cortante', alcance: '—', pericia: 'Luta', atributoDano: 'Força', bonusAtaque: 0 },
  { nome: 'Machado', dano: '1d8', critico: 20, multiplicador: 3, tipoDano: 'Cortante', alcance: '—', pericia: 'Luta', atributoDano: 'Força', bonusAtaque: 0 },
  { nome: 'Pistola', dano: '1d12', critico: 18, multiplicador: 2, tipoDano: 'Balístico', alcance: 'Curto', pericia: 'Pontaria', atributoDano: 'Agilidade', bonusAtaque: 0 },
  { nome: 'Revólver', dano: '2d6', critico: 19, multiplicador: 3, tipoDano: 'Balístico', alcance: 'Curto', pericia: 'Pontaria', atributoDano: 'Agilidade', bonusAtaque: 0 },
  { nome: 'Espingarda', dano: '4d6', critico: 20, multiplicador: 3, tipoDano: 'Balístico', alcance: 'Curto', pericia: 'Pontaria', atributoDano: 'Agilidade', bonusAtaque: 0 },
  { nome: 'Fuzil de Assalto', dano: '2d10', critico: 19, multiplicador: 2, tipoDano: 'Balístico', alcance: 'Médio', pericia: 'Pontaria', atributoDano: 'Agilidade', bonusAtaque: 0 },
  { nome: 'Rifle de Precisão', dano: '2d10', critico: 19, multiplicador: 3, tipoDano: 'Balístico', alcance: 'Longo', pericia: 'Pontaria', atributoDano: 'Agilidade', bonusAtaque: 0 },
];
