// Catálogo de Habilidades — Ordem Paranormal RPG 1ª Edição (livro de regras 0.2)
// Campos: nome, classe, categoria, nex, pe, desc
// CORREÇÃO: Médico de Campo 99% = Reanimação; Eu Conheço um Cara = Negociador 65%
const HABILIDADES_CATALOG = [
  // ===== COMBATENTE — HABILIDADE BASE + PODERES =====
  { nome: 'Ataque Especial', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '5%', pe: '2+ PE',
    desc: 'Quando faz um ataque, você pode gastar 2 PE para receber +5 no teste de ataque ou na rolagem de dano. Conforme avança de NEX, pode gastar +1 PE para receber mais bônus de +5 (NEX 25%: 3 PE / +10; NEX 55%: 4 PE / +15; NEX 85%: 5 PE / +20). Cada +5 pode ser aplicado em ataque ou dano.' },
  { nome: 'Acuidade com Arma', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Quando usa uma arma leve de corpo a corpo ou uma arma de arremesso, você pode usar sua Agilidade em vez de Força nos testes de ataque e rolagens de dano. Pré-requisito: Agi 2.' },
  { nome: 'Armamento Pesado', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Você recebe proficiência com Armas Pesadas.' },
  { nome: 'Ataque de Oportunidade', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '1 PE',
    desc: 'Sempre que um inimigo sair voluntariamente de um espaço adjacente ao seu, você pode gastar uma reação e 1 PE para realizar um ataque contra ele.' },
  { nome: 'Combater com Duas Armas', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Se estiver usando duas armas (e pelo menos uma for leve) e fizer a ação agredir, você pode fazer dois ataques, um com cada arma. Se fizer isso, sofre –1d em todos os testes de ataque até o seu próximo turno. Pré-requisitos: Agi 3, treinado em Luta ou Pontaria.' },
  { nome: 'Combate Defensivo', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Quando usa a ação agredir, você pode combater defensivamente. Se fizer isso, até seu próximo turno, sofre –1d em todos os testes de ataque, mas recebe +5 na Defesa. Pré-requisito: Int 2.' },
  { nome: 'Golpe Demolidor', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '1 PE',
    desc: 'Quando usa a manobra quebrar ou ataca um objeto, você pode gastar 1 PE para causar dois dados de dano extra do mesmo tipo de sua arma. Pré-requisitos: For 2, treinado em Luta.' },
  { nome: 'Golpe Pesado', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'O dano de suas armas corpo a corpo aumenta em um passo.' },
  { nome: 'Incansável', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '2 PE',
    desc: 'Uma vez por cena, você pode gastar 2 PE para fazer uma ação de investigação adicional, mas deve usar Força ou Agilidade como atributo-base do teste.' },
  { nome: 'Presteza Atlética', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '1 PE',
    desc: 'Quando faz um teste de Facilitar a Investigação, você pode gastar 1 PE para usar Força ou Agilidade no lugar do atributo-base da perícia. Se passar no teste, o próximo aliado que usar seu bônus também recebe +1d no teste.' },
  { nome: 'Proteção Pesada', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Você recebe proficiência com Proteções Pesadas. Pré-requisito: NEX 30%.' },
  { nome: 'Reflexos Defensivos', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Você recebe +5 em Defesa e em testes de resistência contra inimigos em alcance curto. Pré-requisitos: Agi 2.' },
  { nome: 'Saque Rápido', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Você pode sacar ou guardar itens como uma ação livre (em vez de ação de movimento). Além disso, a ação que você gasta para recarregar uma arma de disparo diminui em uma categoria. Pré-requisito: treinado em Iniciativa.' },
  { nome: 'Segurar o Gatilho', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '1+ PE',
    desc: 'Ao acertar um ataque com uma arma de fogo, você pode fazer outro contra o mesmo alvo, pagando PE igual à quantidade de ataques já realizados no turno (1º extra: 1 PE; 2º: +2 PE...). Pré-requisito: NEX 60%.' },
  { nome: 'Sentido Tático', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '2 PE',
    desc: 'Você pode gastar uma ação de movimento e 2 PE para analisar o ambiente. Recebe +5 em Defesa e em testes de resistência até o final da cena. Pré-requisitos: treinado em Percepção e Tática.' },
  { nome: 'Tanque de Guerra', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Se estiver usando uma proteção pesada, a Defesa e a resistência a dano que ela fornece aumentam em +2. Pré-requisito: Proteção Pesada.' },
  { nome: 'Tiro Certeiro', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Se estiver usando uma arma de disparo, você soma sua Agilidade nas rolagens de dano e ignora a penalidade contra alvos em combate corpo a corpo. Pré-requisito: treinado em Pontaria.' },
  { nome: 'Tiro de Cobertura', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '1 PE',
    desc: 'Você pode gastar uma ação padrão e 1 PE para disparar e forçar o alvo a se proteger (Pontaria vs Vontade). Se vencer, o alvo não pode sair do lugar e sofre –5 em testes de ataque até seu próximo turno.' },
  { nome: 'Transcender', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Escolha um poder paranormal. Você recebe o poder escolhido, perdendo Sanidade como normal. Pode escolher este poder várias vezes.' },
  { nome: 'Treinamento em Perícia', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Escolha duas perícias. Você se torna treinado nelas. A partir de NEX 35% pode subir para veterano; a partir de NEX 70% para expert. Pode escolher várias vezes.' },

  // ===== COMBATENTE — ANIQUILADOR =====
  { nome: 'A Favorita', classe: 'Combatente', categoria: 'Aniquilador', nex: '10%', pe: '—',
    desc: 'Escolha uma arma favorita. Categoria reduzida em I e ocupa 1 espaço a menos (mín. 0). Em NEX 40% −II, 65% −III, 99% −IV.' },
  { nome: 'Técnica Secreta', classe: 'Combatente', categoria: 'Aniquilador', nex: '40%', pe: '2+ PE',
    desc: 'Ao atacar com a favorita, gaste 2 PE para aplicar efeito (Amplo ou Destruidor). +2 PE por efeito adicional.' },
  { nome: 'Técnica Sublime', classe: 'Combatente', categoria: 'Aniquilador', nex: '65%', pe: '—',
    desc: 'Novos efeitos na Técnica Secreta: Letal (+2 margem; 2x = +5) e Perfurante (ignora até 5 RD).' },
  { nome: 'Máquina de Matar', classe: 'Combatente', categoria: 'Aniquilador', nex: '99%', pe: '—',
    desc: 'Arma favorita: +2 na margem de ameaça e dano aumenta em um passo.' },

  // ===== COMBATENTE — COMANDANTE DE CAMPO =====
  { nome: 'Inspirar Confiança', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '10%', pe: '2 PE',
    desc: 'Reação + 2 PE: um aliado em alcance curto pode rolar novamente um teste recém realizado.' },
  { nome: 'Estrategista', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '40%', pe: '1 PE / aliado',
    desc: 'Ação padrão + 1 PE por aliado (limite = Intelecto): no próximo turno cada aliado direcionado ganha uma ação de movimento.' },
  { nome: 'Brecha na Guarda', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '65%', pe: '2 PE',
    desc: '1x por rodada, quando aliado causa dano em inimigo em alcance curto: reação + 2 PE para você ou outro aliado fazer ataque adicional no mesmo inimigo.' },
  { nome: 'Oficial Comandante', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '99%', pe: '5 PE',
    desc: 'Ação completa + 5 PE: cada aliado em alcance médio recebe uma ação padrão adicional no próximo turno.' },

  // ===== COMBATENTE — GUERREIRO =====
  { nome: 'Técnica Letal', classe: 'Combatente', categoria: 'Guerreiro', nex: '10%', pe: '—',
    desc: '+2 na margem de ameaça com todos os ataques corpo a corpo.' },
  { nome: 'Revidar', classe: 'Combatente', categoria: 'Guerreiro', nex: '40%', pe: '2 PE',
    desc: 'Ao bloquear um ataque, reação + 2 PE: faz um ataque corpo a corpo no inimigo que o atacou.' },
  { nome: 'Força Opressora', classe: 'Combatente', categoria: 'Guerreiro', nex: '65%', pe: '1 PE',
    desc: 'Ao acertar corpo a corpo, gaste 1 PE para manobra derrubar ou empurrar como ação livre (+5 no empurrão por cada 10 de dano). Se derrubar, +1 PE para ataque adicional no alvo caído.' },
  { nome: 'Potência Máxima', classe: 'Combatente', categoria: 'Guerreiro', nex: '99%', pe: '—',
    desc: 'Com Ataque Especial em armas corpo a corpo, todos os bônus numéricos são dobrados.' },

  // ===== COMBATENTE — OPERAÇÕES ESPECIAIS =====
  { nome: 'Iniciativa Aprimorada', classe: 'Combatente', categoria: 'Operações Especiais', nex: '10%', pe: '—',
    desc: 'Você recebe +5 em Iniciativa.' },
  { nome: 'Ataque Extra', classe: 'Combatente', categoria: 'Operações Especiais', nex: '40%', pe: '2 PE',
    desc: '1x por rodada, ao fazer um ataque, gaste 2 PE para fazer um ataque adicional.' },
  { nome: 'Surto de Adrenalina', classe: 'Combatente', categoria: 'Operações Especiais', nex: '65%', pe: '5 PE',
    desc: '1x por rodada: gaste 5 PE para realizar uma ação padrão ou de movimento adicional.' },
  { nome: 'Sempre Alerta', classe: 'Combatente', categoria: 'Operações Especiais', nex: '99%', pe: '—',
    desc: 'Você recebe uma ação padrão adicional no início de cada cena de combate.' },

  // ===== COMBATENTE — TROPA DE CHOQUE =====
  { nome: 'Casca Grossa', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '10%', pe: '—',
    desc: '+1 PV por cada 5% de NEX. Ao bloquear, soma Vigor na RD recebida.' },
  { nome: 'Cai Dentro', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '40%', pe: '1 PE',
    desc: 'Quando oponente em alcance curto ataca aliado: reação + 1 PE; oponente faz Vontade (DT Vig) ou deve atacá-lo em vez do aliado.' },
  { nome: 'Duro de Matar', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '65%', pe: '2 PE',
    desc: 'Ao sofrer dano não mágico: reação + 2 PE para reduzir o dano à metade. Em NEX 99% também vale para dano mágico.' },
  { nome: 'Inquebrável', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '99%', pe: '—',
    desc: 'Machucado: +10 Defesa e RD 5. Morrendo: não fica indefeso e ainda pode realizar ações.' },

  // ===== ESPECIALISTA — BASE + PODERES =====
  { nome: 'Eclético', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '5%', pe: '2 PE',
    desc: 'Ao fazer um teste de perícia, gaste 2 PE para receber os benefícios de ser treinado nela.' },
  { nome: 'Perito', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '5%', pe: '2+ PE',
    desc: 'Escolha 2 perícias treinadas (exceto Luta e Pontaria). Gaste 2 PE para +1d6 no teste. Escala: NEX 25% 3 PE/+1d8; 55% 4 PE/+1d10; 85% 5 PE/+1d12.' },
  { nome: 'Acuidade com Arma', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Com arma leve corpo a corpo ou de arremesso, usa Agilidade em vez de Força. Pré: Agi 2.' },
  { nome: 'Balística Avançada', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Proficiência com armas táticas de fogo e +2 em dano com essas armas.' },
  { nome: 'Conhecimento Aplicado', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '2 PE',
    desc: 'Em teste de perícia (exceto Luta e Pontaria), gaste 2 PE para mudar o atributo-base para Intelecto. Pré: Int 2.' },
  { nome: 'Hacker', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: '+5 em Tecnologia para invadir sistemas; tempo de hack reduzido a ação completa. Pré: treinado em Tecnologia.' },
  { nome: 'Mãos Rápidas', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '1 PE',
    desc: 'Em teste de Crime, gaste 1 PE para fazê-lo como ação livre. Pré: Agi 3, treinado em Crime.' },
  { nome: 'Mochila de Utilidades', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Um kit de perícia à escolha conta como categoria abaixo e ocupa 1 espaço a menos.' },
  { nome: 'Movimento Tático', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '1 PE',
    desc: 'Gaste 1 PE para ignorar penalidade de terreno difícil e receber deslocamento de escalada igual ao seu até o fim do turno. Pré: treinado em Atletismo.' },
  { nome: 'Na Trilha Certa', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '1+ PE',
    desc: 'Ao ter sucesso em procurar pistas, gaste 1 PE para +1d no próximo teste (cumulativo).' },
  { nome: 'Nerd', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '2 PE',
    desc: '1x por cena: gaste 2 PE e teste Atualidades (DT 20). Se passar, recebe informação útil para a cena.' },
  { nome: 'Ninja Urbano', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Proficiência com armas táticas corpo a corpo e +2 em dano com essas armas.' },
  { nome: 'Pensamento Ágil', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '2 PE',
    desc: '1x por rodada em cena de investigação: gaste 2 PE para ação adicional de procurar pistas.' },
  { nome: 'Perito em Explosivos', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Soma Intelecto na DT para resistir aos seus explosivos e pode excluir alvos iguais ao seu Int.' },
  { nome: 'Primeira Impressão', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: '+2d no primeiro teste de Diplomacia, Enganação, Intimidação ou Intuição da cena.' },
  { nome: 'Transcender', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Escolha um poder paranormal. Você recebe o poder, perdendo Sanidade como normal. Pode escolher várias vezes.' },
  { nome: 'Treinamento em Perícia', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Escolha duas perícias e torne-se treinado. Em NEX alto pode subir para veterano/expert. Pode escolher várias vezes.' },

  // ===== ESPECIALISTA — ATIRADOR DE ELITE =====
  { nome: 'Mira de Elite', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '10%', pe: '—',
    desc: 'Proficiência com armas de fogo longas e soma Intelecto no dano com essas armas.' },
  { nome: 'Disparo Letal', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '40%', pe: '1 PE',
    desc: 'Ao mirar, gaste 1 PE para +2 na margem de ameaça do próximo ataque até o fim do próximo turno.' },
  { nome: 'Disparo Impactante', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '65%', pe: '2 PE',
    desc: 'Com arma de fogo de calibre médio ou grosso, gaste 2 PE para fazer manobras (derrubar, desarmar, empurrar, quebrar) à distância.' },
  { nome: 'Atirar para Matar', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '99%', pe: '—',
    desc: 'Em acerto crítico com arma de fogo, causa dano máximo sem rolar dados.' },

  // ===== ESPECIALISTA — INFILTRADOR =====
  { nome: 'Ataque Furtivo', classe: 'Especialista', categoria: 'Infiltrador', nex: '10%', pe: '1 PE',
    desc: '1x por rodada, contra alvo desprevenido ou flanqueado: gaste 1 PE para +1d6 de dano. Escala: 40% +2d6, 65% +3d6, 99% +4d6.' },
  { nome: 'Gatuno', classe: 'Especialista', categoria: 'Infiltrador', nex: '40%', pe: '—',
    desc: '+5 em Atletismo e Crime. Pode se mover em velocidade normal enquanto escondido, sem penalidade.' },
  { nome: 'Assassinar', classe: 'Especialista', categoria: 'Infiltrador', nex: '65%', pe: '3 PE',
    desc: 'Ação de movimento + 3 PE: analisa alvo. Até o fim do próximo turno, primeiro Ataque Furtivo tem dados extras dobrados; alvo pode ficar inconsciente/morrendo (Fortitude DT Agi evita).' },
  { nome: 'Sombra Fugaz', classe: 'Especialista', categoria: 'Infiltrador', nex: '99%', pe: '3 PE',
    desc: 'Em teste de Furtividade após ação chamativa, gaste 3 PE para não sofrer a penalidade de –20.' },

  // ===== ESPECIALISTA — MÉDICO DE CAMPO =====
  { nome: 'Paramédico', classe: 'Especialista', categoria: 'Médico de Campo', nex: '10%', pe: '2+ PE',
    desc: 'Você pode usar uma ação padrão e 2 PE para curar 2d10 pontos de vida de um aliado adjacente. Pode curar +1d10 PV em NEX 40%, 65% e 99%, gastando +1 PE por dado adicional. Especial: precisa ser treinado em Medicina.' },
  { nome: 'Equipe de Trauma', classe: 'Especialista', categoria: 'Médico de Campo', nex: '40%', pe: '2 PE',
    desc: 'Você pode usar uma ação padrão e 2 PE para remover uma condição negativa (exceto morrendo) de um aliado adjacente.' },
  { nome: 'Resgate', classe: 'Especialista', categoria: 'Médico de Campo', nex: '65%', pe: '—',
    desc: 'Uma vez por rodada, se estiver em alcance curto de um aliado machucado ou morrendo, você pode se aproximar do aliado com uma ação livre. Além disso, sempre que curar PV ou remover condições do aliado, você e o aliado recebem +5 na Defesa até o início de seu próximo turno. Carregar um personagem ocupa metade dos espaços.' },
  { nome: 'Reanimação', classe: 'Especialista', categoria: 'Médico de Campo', nex: '99%', pe: '10 PE',
    desc: 'Uma vez por cena, você pode gastar uma ação completa e 10 PE para trazer de volta à vida um personagem que tenha morrido na mesma cena (exceto morte por dano massivo).' },

  // ===== ESPECIALISTA — NEGOCIADOR =====
  { nome: 'Lábia de Ouro', classe: 'Especialista', categoria: 'Negociador', nex: '10%', pe: '—',
    desc: 'Você recebe +5 em testes de Diplomacia, Enganação e Intimidação.' },
  { nome: 'Argumento Irrefutável', classe: 'Especialista', categoria: 'Negociador', nex: '40%', pe: '2 PE',
    desc: 'Quando faz um teste de Diplomacia, Enganação ou Intimidação, você pode gastar 2 PE para forçar o alvo a fazer um teste de Vontade (DT Int). Se falhar, o alvo fica abalado ou persuadido conforme a intenção.' },
  { nome: 'Eu Conheço um Cara', classe: 'Especialista', categoria: 'Negociador', nex: '65%', pe: '—',
    desc: 'Uma vez por missão, você pode ativar sua rede de contatos para pedir um favor (trocar equipamento do grupo, local de descanso, resgate etc.). O mestre tem a palavra final.' },
  { nome: 'Truque de Mestre', classe: 'Especialista', categoria: 'Negociador', nex: '99%', pe: '5 PE',
    desc: 'Você pode gastar 5 PE para simular o efeito de qualquer habilidade que você tenha visto um de seus aliados usar durante a cena. Você ignora pré-requisitos, mas ainda paga os custos (ações, PE, materiais).' },

  // ===== ESPECIALISTA — TÉCNICO =====
  { nome: 'Ferramentas Improvisadas', classe: 'Especialista', categoria: 'Técnico', nex: '10%', pe: '—',
    desc: 'Você pode improvisar kits de perícia com materiais disponíveis e recebe +5 em testes de Ofício e Tecnologia relacionados a manutenção e reparo.' },
  { nome: 'Remendão', classe: 'Especialista', categoria: 'Técnico', nex: '40%', pe: '2 PE',
    desc: 'Você pode gastar uma ação padrão e 2 PE para reparar um item danificado ou restaurar equipamentos.' },
  { nome: 'Sabotagem', classe: 'Especialista', categoria: 'Técnico', nex: '65%', pe: '2 PE',
    desc: 'Você pode gastar uma ação padrão e 2 PE para sabotar um equipamento ou arma em alcance curto.' },
  { nome: 'Engenheiro de Campo', classe: 'Especialista', categoria: 'Técnico', nex: '99%', pe: '—',
    desc: 'Você improvisamodificações temporárias em armas/equipamentos e reduz pela metade o tempo de reparos.' },

  // ===== OCULTISTA — BASE + PODERES =====
  { nome: 'Escolhido pelo Outro Lado', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '5%', pe: '—',
    desc: 'Começa conhecendo rituais de 1º círculo e pode aprender mais conforme o NEX.' },
  { nome: 'Camuflar Ocultismo', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '+2 PE',
    desc: 'Ação livre: esconde símbolos e sigilos. Ao lançar ritual, pode gastar +2 PE para lançar só com concentração (sem gestos/fala).' },
  { nome: 'Envolto em Mistério', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Aparência e postura dificultam leituras sociais ligadas ao mistério que o cerca.' },
  { nome: 'Intuição Paranormal', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Ao facilitar investigação, soma Intelecto ou Presença no teste (à escolha).' },
  { nome: 'Mestre em Elemento', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Escolha um Elemento. Custo de rituais desse Elemento −1 PE. Pré: Especialista em Elemento, NEX 45%.' },
  { nome: 'Ritual Potente', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Soma Intelecto nas rolagens de dano ou cura de rituais. Pré: Int 1.' },
  { nome: 'Ritual Predileto', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Escolha um ritual conhecido: custo −1 PE (acumula com outras reduções).' },
  { nome: 'Tatuagem Ritualística', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Símbolos na pele reduzem −1 PE o custo de rituais de alcance pessoal com você como alvo.' },
  { nome: 'Transcender', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Escolha um poder paranormal. Você recebe o poder, perdendo Sanidade como normal. Pode escolher várias vezes.' },
  { nome: 'Treinamento em Perícia', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Escolha duas perícias e torne-se treinado. Em NEX alto pode subir para veterano/expert.' },

  // ===== OCULTISTA — CONDUÍTE =====
  { nome: 'Ampliar Ritual', classe: 'Ocultista', categoria: 'Conduíte', nex: '10%', pe: '+2 PE',
    desc: 'Ao lançar ritual, gaste +2 PE para aumentar alcance em um passo ou dobrar a área.' },
  { nome: 'Acelerar Ritual', classe: 'Ocultista', categoria: 'Conduíte', nex: '40%', pe: '+4 PE',
    desc: '1x por rodada: gaste +4 PE para conjurar um ritual como ação livre.' },
  { nome: 'Anular Ritual', classe: 'Ocultista', categoria: 'Conduíte', nex: '65%', pe: 'variável',
    desc: 'Quando for alvo de ritual, gaste PE igual ao custo do ritual e teste Ocultismo oposto. Se vencer, anula o ritual.' },
  { nome: 'Canalizar o Medo', classe: 'Ocultista', categoria: 'Conduíte', nex: '99%', pe: '—',
    desc: 'Você aprende o ritual Canalizar o Medo.' },

  // ===== OCULTISTA — FLAGELADOR =====
  { nome: 'Dor é Poder', classe: 'Ocultista', categoria: 'Flagelador', nex: '10%', pe: '—',
    desc: 'Quando sofre dano, pode transformar parte da dor em poder para rituais.' },
  { nome: 'Sacrifício Controlado', classe: 'Ocultista', categoria: 'Flagelador', nex: '40%', pe: '—',
    desc: 'Pode gastar PV ou SAN de forma controlada para potencializar rituais ou recuperar PE.' },
  { nome: 'Martírio Útil', classe: 'Ocultista', categoria: 'Flagelador', nex: '65%', pe: '—',
    desc: 'Efeitos de autoflagelo concedem PE ou ampliam a DT de rituais.' },
  { nome: 'Sangue do Outro Lado', classe: 'Ocultista', categoria: 'Flagelador', nex: '99%', pe: '—',
    desc: 'Sacrifício supremo: rituais poderosos a alto custo de PV/SAN, com efeitos amplificados.' },

  // ===== OCULTISTA — GRADUADO =====
  { nome: 'Estudante Avançado', classe: 'Ocultista', categoria: 'Graduado', nex: '10%', pe: '—',
    desc: 'Aprende rituais adicionais ou reduz requisitos de círculo em certas condições.' },
  { nome: 'Tese Ocultista', classe: 'Ocultista', categoria: 'Graduado', nex: '40%', pe: '—',
    desc: 'Especialização em um tipo de ritual: bônus em DT ou redução de PE.' },
  { nome: 'Doutorado do Medo', classe: 'Ocultista', categoria: 'Graduado', nex: '65%', pe: '—',
    desc: 'Conhecimento profundo permite improvisar efeitos rituais menores.' },
  { nome: 'Arquimago da Ordem', classe: 'Ocultista', categoria: 'Graduado', nex: '99%', pe: '—',
    desc: 'Máximo domínio: mais rituais conhecidos e conjuração otimizada.' },

  // ===== OCULTISTA — INTUITIVO =====
  { nome: 'Sexto Sentido', classe: 'Ocultista', categoria: 'Intuitivo', nex: '10%', pe: '—',
    desc: 'Percebe manifestações e intenções paranormais com mais facilidade.' },
  { nome: 'Presságio', classe: 'Ocultista', categoria: 'Intuitivo', nex: '40%', pe: '—',
    desc: '1x por cena: recebe uma visão ou vantagem em um teste crucial.' },
  { nome: 'Sintonizar Entidade', classe: 'Ocultista', categoria: 'Intuitivo', nex: '65%', pe: '—',
    desc: 'Conecta-se temporariamente a uma entidade para bônus de elemento.' },
  { nome: 'Voz do Outro Lado', classe: 'Ocultista', categoria: 'Intuitivo', nex: '99%', pe: '—',
    desc: 'Intuição quase infalível para detectar e antecipar o paranormal.' },

  // ===== OCULTISTA — LÂMINA PARANORMAL =====
  { nome: 'Amaldiçoar Arma', classe: 'Ocultista', categoria: 'Lâmina Paranormal', nex: '10%', pe: '—',
    desc: 'Aprende o ritual Amaldiçoar Arma (ou custo −1 PE). Pode usar Ocultismo no lugar de Luta/Pontaria com a arma amaldiçoada.' },
  { nome: 'Gladiador Paranormal', classe: 'Ocultista', categoria: 'Lâmina Paranormal', nex: '40%', pe: '—',
    desc: 'Ao acertar ataque corpo a corpo, recebe 2 PE temporários (limite por cena).' },
  { nome: 'Lâmina Viva', classe: 'Ocultista', categoria: 'Lâmina Paranormal', nex: '65%', pe: '2 PE',
    desc: '1x por rodada, ao lançar ritual de ação padrão, gaste 2 PE para fazer um ataque corpo a corpo como ação livre.' },
  { nome: 'Avatar da Lâmina', classe: 'Ocultista', categoria: 'Lâmina Paranormal', nex: '99%', pe: '—',
    desc: 'Arma amaldiçoada se torna extensão de você: bônus permanentes de dano e efeitos paranormais.' }
];

const HABILIDADES_CATEGORIAS = {
  'Combatente': ['Poderes de Combatente', 'Aniquilador', 'Comandante de Campo', 'Guerreiro', 'Operações Especiais', 'Tropa de Choque'],
  'Especialista': ['Poderes de Especialista', 'Atirador de Elite', 'Infiltrador', 'Médico de Campo', 'Negociador', 'Técnico'],
  'Ocultista': ['Poderes de Ocultista', 'Conduíte', 'Flagelador', 'Graduado', 'Intuitivo', 'Lâmina Paranormal']
};
