// Catálogo de Habilidades — Ordem Paranormal RPG 1ª Edição
// Campos: nome, classe, categoria, nex, pe, desc
// Atualizado com textos oficiais do Livro Básico (Combatente, Especialista, Ocultista)
const HABILIDADES_CATALOG = [
  { nome: 'Habilidade de Trilha', classe: 'Combatente', categoria: 'Habilidades de Classe', nex: '10%', pe: '—',
    desc: 'Em NEX 10% escolhe a trilha e recebe o 1º poder. Ganha novos poderes em 40%, 65% e 99%.' },
  { nome: 'Poder de Combatente', classe: 'Combatente', categoria: 'Habilidades de Classe', nex: '15%', pe: '—',
    desc: 'Em NEX 15%, 30% e a cada 15% depois, escolhe um poder de Combatente.' },
  { nome: 'Aumento de Atributo', classe: 'Combatente', categoria: 'Habilidades de Classe', nex: '20%', pe: '—',
    desc: '+1 em um atributo em NEX 20%, 50%, 80% e 95%, até o máximo de 5.' },
  { nome: 'Grau de Treinamento', classe: 'Combatente', categoria: 'Habilidades de Classe', nex: '35%', pe: '—',
    desc: 'Em NEX 35% e 70%, sobe um grau em 2 + Intelecto perícias.' },
  { nome: 'Versatilidade', classe: 'Combatente', categoria: 'Habilidades de Classe', nex: '50%', pe: '—',
    desc: 'Em NEX 50%, escolhe entre um poder de Combatente ou o 1º poder de outra trilha de Combatente.' },
  { nome: 'Artista Marcial', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Desarmado causa 1d6, letal e ágil. Sobe para 1d8 em NEX 35% e 1d10 em 70%.' },
  { nome: 'Ataque Especial', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '5%', pe: '2+ PE',
    desc: 'Ao atacar, gasta 2 PE para +5 no ataque ou no dano. Ganha mais bônus de +5 por +1 PE: 3 PE/+10 (NEX 25%), 4 PE/+15 (55%) e 5 PE/+20 (85%).' },
  { nome: 'Acuidade com Arma', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Com arma leve corpo a corpo ou de arremesso, usa Agilidade em vez de Força. Pré: Agi 2.' },
  { nome: 'Armamento Pesado', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Proficiência com armas pesadas. Pré: For 2.' },
  { nome: 'Ataque de Oportunidade', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '1 PE',
    desc: 'Quando um ser sai voluntariamente de um espaço adjacente, reação + 1 PE para um ataque corpo a corpo.' },
  { nome: 'Combater com Duas Armas', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Duas armas (uma leve), ação agredir, dois ataques. Sofre –1 dado em todos os ataques até o próximo turno. Pré: Agi 3, treinado em Luta ou Pontaria.' },
  { nome: 'Combate Defensivo', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Ao agredir, –1 dado nos ataques até o próximo turno e +5 na Defesa. Pré: Int 2.' },
  { nome: 'Golpe Demolidor', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '1 PE',
    desc: 'Ao quebrar ou atacar objeto, 1 PE para 2 dados de dano extra. Pré: For 2, treinado em Luta.' },
  { nome: 'Golpe Pesado', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Arma corpo a corpo empunhada causa +1 dado de dano do mesmo tipo.' },
  { nome: 'Incansável', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '2 PE',
    desc: '1x por cena, 2 PE para uma ação de investigação adicional, usando For ou Agi como atributo-base.' },
  { nome: 'Presteza Atlética', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '1 PE',
    desc: 'Ao facilitar investigação, 1 PE para usar For ou Agi no lugar do atributo-base. Se passar, o próximo aliado que usar o bônus também ganha +1 dado.' },
  { nome: 'Proteção Pesada', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '30%', pe: '—',
    desc: 'Proficiência com proteções pesadas. Pré: NEX 30%.' },
  { nome: 'Reflexos Defensivos', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: '+2 na Defesa e nos testes de resistência. Pré: Agi 2.' },
  { nome: 'Saque Rápido', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Sacar ou guardar itens vira ação livre. Com a regra opcional de munição, 1x por rodada recarrega arma de disparo como ação livre. Pré: treinado em Iniciativa.' },
  { nome: 'Segurar o Gatilho', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '60%', pe: '2+ PE',
    desc: 'Ao acertar com arma de fogo, pode atacar de novo o mesmo alvo, pagando 2 PE por cada ataque já feito no turno. Pré: NEX 60%.' },
  { nome: 'Sentido Tático', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '2 PE',
    desc: 'Ação de movimento + 2 PE. Recebe bônus em Defesa e resistência igual ao Intelecto até o fim da cena. Pré: Int 2, treinado em Percepção e Tática.' },
  { nome: 'Tanque de Guerra', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Com proteção pesada: +2 Defesa e RD da proteção. Pré: Proteção Pesada.' },
  { nome: 'Tiro Certeiro', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Com arma de disparo: soma Agilidade no dano e ignora penalidade em combate corpo a corpo. Pré: treinado em Pontaria.' },
  { nome: 'Tiro de Cobertura', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '1 PE',
    desc: 'Ação padrão + 1 PE: força alvo a se proteger (Pontaria vs Vontade); alvo não sai do lugar e sofre –5 em ataques.' },
  { nome: 'Transcender', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Recebe um poder paranormal (paga SAN). Pode escolher várias vezes.' },
  { nome: 'Treinamento em Perícia', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', pe: '—',
    desc: 'Torna-se treinado em duas perícias (pode subir para veterano/expert com NEX).' },
  { nome: 'A Favorita', classe: 'Combatente', categoria: 'Aniquilador', nex: '10%', pe: '—',
    desc: 'Escolhe uma arma favorita (ex: katana, fuzil de assalto): categoria reduzida em I.' },
  { nome: 'Técnica Secreta', classe: 'Combatente', categoria: 'Aniquilador', nex: '40%', pe: '2+ PE',
    desc: 'Categoria da favorita reduzida em II; ao atacar com ela, 2 PE por efeito (cumulável): Amplo (atinge um alvo adicional adjacente, mesmo teste) ou Destruidor (+1 no multiplicador de crítico).' },
  { nome: 'Técnica Sublime', classe: 'Combatente', categoria: 'Aniquilador', nex: '65%', pe: '—',
    desc: 'Ganha os efeitos Letal (+2 na margem de ameaça; pode escolher 2x = +5) e Perfurante (ignora até 5 de RD de qualquer tipo) na lista de efeitos da favorita.' },
  { nome: 'Máquina de Matar', classe: 'Combatente', categoria: 'Aniquilador', nex: '99%', pe: '—',
    desc: 'Categoria da favorita reduzida em III; +2 na margem de ameaça e +1 dado de dano do mesmo tipo.' },
  { nome: 'Inspirar Confiança', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '10%', pe: '2 PE',
    desc: 'Reação + 2 PE: um aliado em alcance curto rerrola um teste recém feito.' },
  { nome: 'Estrategista', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '40%', pe: '1 PE/aliado',
    desc: 'Ação padrão + 1 PE por aliado (até seu Intelecto) em alcance curto; eles ganham ação de movimento extra no próximo turno.' },
  { nome: 'Brecha na Guarda', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '65%', pe: '2 PE',
    desc: 'Reação + 2 PE: quando aliado causa dano num inimigo em alcance curto, permite um ataque adicional dele ou de outro aliado contra o mesmo inimigo. Alcance de Inspirar Confiança/Estrategista sobe para médio.' },
  { nome: 'Oficial Comandante', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '99%', pe: '5 PE',
    desc: 'Ação padrão + 5 PE: dá ação padrão extra no próximo turno de cada aliado visível em alcance médio.' },
  { nome: 'Técnica Letal', classe: 'Combatente', categoria: 'Guerreiro', nex: '10%', pe: '—',
    desc: '+2 na margem de ameaça com ataques corpo a corpo.' },
  { nome: 'Revidar', classe: 'Combatente', categoria: 'Guerreiro', nex: '40%', pe: '2 PE',
    desc: 'Reação + 2 PE ao bloquear: faz um ataque corpo a corpo no atacante.' },
  { nome: 'Força Opressora', classe: 'Combatente', categoria: 'Guerreiro', nex: '65%', pe: '1 PE',
    desc: 'Ao acertar corpo a corpo, 1 PE faz uma manobra (derrubar ou empurrar) como ação livre; empurrar dá +5 por cada 10 de dano causado; derrubar com sucesso permite +1 PE para atacar de novo o alvo caído.' },
  { nome: 'Potência Máxima', classe: 'Combatente', categoria: 'Guerreiro', nex: '99%', pe: '—',
    desc: 'Bônus numéricos do Ataque Especial com armas corpo a corpo são dobrados.' },
  { nome: 'Iniciativa Aprimorada', classe: 'Combatente', categoria: 'Operações Especiais', nex: '10%', pe: '—',
    desc: '+5 em Iniciativa e ação de movimento extra na 1ª rodada.' },
  { nome: 'Ataque Extra', classe: 'Combatente', categoria: 'Operações Especiais', nex: '40%', pe: '2 PE',
    desc: '1x/rodada, 2 PE dá um ataque adicional.' },
  { nome: 'Surto de Adrenalina', classe: 'Combatente', categoria: 'Operações Especiais', nex: '65%', pe: '5 PE',
    desc: '1x/rodada, 5 PE dá uma ação padrão ou de movimento adicional.' },
  { nome: 'Sempre Alerta', classe: 'Combatente', categoria: 'Operações Especiais', nex: '99%', pe: '—',
    desc: 'Ação padrão extra no início de toda cena de combate.' },
  { nome: 'Casca Grossa', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '10%', pe: '—',
    desc: '+1 PV por 5% de NEX; ao bloquear, soma Vigor na resistência a dano.' },
  { nome: 'Cai Dentro', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '40%', pe: '1 PE',
    desc: 'Reação + 1 PE: oponente em alcance curto atacando um aliado faz Vontade (DT Vig) ou é forçado a atacar você em vez dele.' },
  { nome: 'Duro de Matar', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '65%', pe: '2 PE',
    desc: 'Reação + 2 PE reduz dano não paranormal à metade (paranormal também a partir de NEX 85%).' },
  { nome: 'Inquebrável', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '99%', pe: '—',
    desc: 'Enquanto machucado, +5 Defesa e RD 5; enquanto morrendo, não fica indefeso e pode agir normalmente (ainda segue as regras de morte).' },
  { nome: 'Habilidade de Trilha', classe: 'Especialista', categoria: 'Habilidades de Classe', nex: '10%', pe: '—',
    desc: 'Em NEX 10% escolhe a trilha e recebe o 1º poder. Ganha novos poderes em 40%, 65% e 99%.' },
  { nome: 'Poder de Especialista', classe: 'Especialista', categoria: 'Habilidades de Classe', nex: '15%', pe: '—',
    desc: 'Em NEX 15%, 30% e a cada 15% depois, escolhe um poder de Especialista.' },
  { nome: 'Aumento de Atributo', classe: 'Especialista', categoria: 'Habilidades de Classe', nex: '20%', pe: '—',
    desc: '+1 em um atributo em NEX 20%, 50%, 80% e 95%, até o máximo de 5.' },
  { nome: 'Grau de Treinamento', classe: 'Especialista', categoria: 'Habilidades de Classe', nex: '35%', pe: '—',
    desc: 'Em NEX 35% e 70%, sobe um grau em 5 + Intelecto perícias.' },
  { nome: 'Versatilidade', classe: 'Especialista', categoria: 'Habilidades de Classe', nex: '50%', pe: '—',
    desc: 'Em NEX 50%, escolhe entre um poder de Especialista ou o 1º poder de outra trilha de Especialista.' },
  { nome: 'Artista Marcial', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Igual ao do Combatente: desarmado 1d6 letal e ágil (1d8 em NEX 35%, 1d10 em 70%); ataques desarmados contam como armas ágeis.' },
  { nome: 'Eclético', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '5%', pe: '2 PE',
    desc: 'Ao testar uma perícia, 2 PE para ter os benefícios de ser treinado nela.' },
  { nome: 'Perito', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '5%', pe: '2+ PE',
    desc: 'Escolhe 2 perícias treinadas (exceto Luta e Pontaria). Ao testá-las, 2 PE para +1d6 no resultado. O dado sobe pagando +1 PE: 3 PE/+1d8 (NEX 25%), 4 PE/+1d10 (55%) e 5 PE/+1d12 (85%).' },
  { nome: 'Engenhosidade', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '40%', pe: '—',
    desc: 'No Eclético, em NEX 40% pode gastar +2 PE para ter os benefícios de veterano. Em 75%, +4 PE para os de expert.' },
  { nome: 'Acuidade com Arma', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Arma leve corpo a corpo/arremesso usa Agilidade. Pré: Agi 2.' },
  { nome: 'Balística Avançada', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Proficiência com armas táticas de fogo e +2 no dano com armas de fogo.' },
  { nome: 'Conhecimento Aplicado', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '2 PE',
    desc: 'Em teste de perícia (exceto Luta e Pontaria), 2 PE para usar Int como atributo-base. Pré: Int 2.' },
  { nome: 'Hacker', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: '+5 em Tecnologia para invadir sistemas, e hackear leva uma ação completa. Pré: treinado em Tecnologia.' },
  { nome: 'Mãos Rápidas', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '1 PE',
    desc: 'Teste de Crime como ação livre por 1 PE. Pré: Agi 3, treinado em Crime.' },
  { nome: 'Mochila de Utilidades', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Um item (exceto arma) conta como uma categoria abaixo e ocupa 1 espaço a menos.' },
  { nome: 'Movimento Tático', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '1 PE',
    desc: '1 PE para ignorar a penalidade de terreno difícil e de escalar até o fim do turno. Pré: treinado em Atletismo.' },
  { nome: 'Na Trilha Certa', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '1 PE',
    desc: 'Ao ter sucesso em teste para procurar pistas, 1 PE para +1 dado no próximo teste. Custos e bônus se acumulam.' },
  { nome: 'Nerd', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '2 PE',
    desc: '1x por cena, 2 PE para teste de Atualidades (DT 20). Se passar, recebe uma informação útil para a cena.' },
  { nome: 'Ninja Urbano', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Proficiência com armas táticas corpo a corpo e de disparo (exceto fogo) e +2 de dano com elas.' },
  { nome: 'Pensamento Ágil', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '2 PE',
    desc: '1x por rodada em investigação, 2 PE para uma ação de procurar pistas adicional.' },
  { nome: 'Perito em Explosivos', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Soma Int na DT dos seus explosivos e exclui da explosão um número de alvos igual ao Int.' },
  { nome: 'Primeira Impressão', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: '+2 dados no primeiro teste de Diplomacia, Enganação, Intimidação ou Intuição da cena.' },
  { nome: 'Transcender', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Escolhe um poder paranormal, mas não ganha Sanidade nesse aumento de NEX. Pode repetir.' },
  { nome: 'Treinamento em Perícia', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', pe: '—',
    desc: 'Treina 2 perícias. A partir de NEX 35% pode subir para veterano e, a partir de 70%, para expert. Pode repetir.' },
  { nome: 'Mira de Elite', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '10%', pe: '—',
    desc: 'Proficiência com armas de fogo de balas longas; soma Intelecto no dano com elas.' },
  { nome: 'Disparo Letal', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '40%', pe: '1 PE',
    desc: 'Ao mirar, 1 PE dá +2 na margem de ameaça do próximo ataque até o fim do próximo turno.' },
  { nome: 'Disparo Impactante', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '65%', pe: '2 PE',
    desc: '2 PE troca o dano do ataque por uma manobra (derrubar, desarmar, empurrar ou quebrar).' },
  { nome: 'Atirar para Matar', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '99%', pe: '—',
    desc: 'Crítico com arma de fogo causa dano máximo sem rolar dados.' },
  { nome: 'Ataque Furtivo', classe: 'Especialista', categoria: 'Infiltrador', nex: '10%', pe: '1 PE',
    desc: '1x/rodada, 1 PE em alvo desprevenido/flanqueado dá +1d6 de dano extra do mesmo tipo da arma (sobe para +2d6 em 40%, +3d6 em 65%, +4d6 em 99%).' },
  { nome: 'Gatuno', classe: 'Especialista', categoria: 'Infiltrador', nex: '40%', pe: '—',
    desc: '+5 em Atletismo e Crime; move-se normalmente ao se esconder, sem penalidade.' },
  { nome: 'Assassinar', classe: 'Especialista', categoria: 'Infiltrador', nex: '65%', pe: '3 PE',
    desc: 'Ação de movimento + 3 PE analisa um alvo em alcance curto; seu próximo Ataque Furtivo nele dobra os dados extras e, se causar dano, deixa o alvo inconsciente ou morrendo à escolha (Fortitude DT Agi evita).' },
  { nome: 'Sombra Fugaz', classe: 'Especialista', categoria: 'Infiltrador', nex: '99%', pe: '3 PE',
    desc: '3 PE remove a penalidade de –OOO em Furtividade após atacar ou agir de forma chamativa.' },
  { nome: 'Paramédico', classe: 'Especialista', categoria: 'Médico de Campo', nex: '10%', pe: '2+ PE',
    desc: 'Ação padrão + 2 PE cura 2d10 PV (mais +1d10 em 40/65/99%, +1 PE por dado extra). Pré-req: treinado em Medicina; precisa de kit de medicina.' },
  { nome: 'Equipe de Trauma', classe: 'Especialista', categoria: 'Médico de Campo', nex: '40%', pe: '2 PE',
    desc: 'Ação padrão + 2 PE remove uma condição negativa (exceto morrendo) de aliado adjacente.' },
  { nome: 'Resgate', classe: 'Especialista', categoria: 'Médico de Campo', nex: '65%', pe: '—',
    desc: '1x/rodada, ação livre se aproxima de aliado machucado/morrendo em alcance curto; curar ou remover condição também dá +5 Defesa a ambos até o próximo turno; carregar alguém custa metade dos espaços.' },
  { nome: 'Reanimação', classe: 'Especialista', categoria: 'Médico de Campo', nex: '99%', pe: '10 PE',
    desc: '1x/cena, ação completa + 10 PE ressuscita alguém morto na mesma cena (exceto morte por dano massivo).' },
  { nome: 'Eloquência', classe: 'Especialista', categoria: 'Negociador', nex: '10%', pe: '1 PE/alvo',
    desc: 'Ação completa + 1 PE por alvo em alcance curto; teste de Diplomacia/Enganação/Intimidação vs Vontade; sucesso deixa fascinado enquanto se concentrar (alvo hostil tem +5 e novo teste por rodada); quem resiste fica imune por 1 dia.' },
  { nome: 'Discurso Motivador', classe: 'Especialista', categoria: 'Negociador', nex: '40%', pe: '4 PE',
    desc: 'Ação padrão + 4 PE dá +O em perícia pra você e aliados em alcance curto até o fim da cena (vira +OO por 8 PE a partir de 65%).' },
  { nome: 'Eu Conheço um Cara', classe: 'Especialista', categoria: 'Negociador', nex: '65%', pe: '—',
    desc: '1x/missão, ativa contatos para um favor grande (trocar equipamento, achar abrigo, ser resgatado — critério do mestre).' },
  { nome: 'Truque de Mestre', classe: 'Especialista', categoria: 'Negociador', nex: '99%', pe: '5 PE',
    desc: '5 PE simula qualquer habilidade que viu um aliado usar na cena (ignora pré-requisitos, mas paga custos normalmente).' },
  { nome: 'Inventário Otimizado', classe: 'Especialista', categoria: 'Técnico', nex: '10%', pe: '—',
    desc: 'Soma Intelecto à Força para calcular carga.' },
  { nome: 'Remendão', classe: 'Especialista', categoria: 'Técnico', nex: '40%', pe: '1 PE',
    desc: 'Ação completa + 1 PE remove a condição quebrado de um equipamento adjacente; equipamento geral tem categoria reduzida em I pra você.' },
  { nome: 'Improvisar', classe: 'Especialista', categoria: 'Técnico', nex: '65%', pe: '2+ PE',
    desc: 'Ação completa + 2 PE (+2 por categoria) cria uma versão funcional temporária de um equipamento geral (inútil no fim da cena).' },
  { nome: 'Preparado para Tudo', classe: 'Especialista', categoria: 'Técnico', nex: '99%', pe: '3 PE/cat.',
    desc: 'Ação de movimento + 3 PE por categoria "lembra" que tinha um item qualquer (exceto armas) no fundo da bolsa.' },
  { nome: 'Habilidade de Trilha', classe: 'Ocultista', categoria: 'Habilidades de Classe', nex: '10%', pe: '—',
    desc: 'Em NEX 10% escolhe a trilha e recebe o 1º poder. Ganha novos poderes em 40%, 65% e 99%.' },
  { nome: 'Poder de Ocultista', classe: 'Ocultista', categoria: 'Habilidades de Classe', nex: '15%', pe: '—',
    desc: 'Em NEX 15%, 30% e a cada 15% depois, escolhe um poder de Ocultista.' },
  { nome: 'Aumento de Atributo', classe: 'Ocultista', categoria: 'Habilidades de Classe', nex: '20%', pe: '—',
    desc: '+1 em um atributo em NEX 20%, 50%, 80% e 95%, até o máximo de 5.' },
  { nome: 'Grau de Treinamento', classe: 'Ocultista', categoria: 'Habilidades de Classe', nex: '35%', pe: '—',
    desc: 'Em NEX 35% e 70%, sobe um grau em perícias conforme a tabela da classe.' },
  { nome: 'Versatilidade', classe: 'Ocultista', categoria: 'Habilidades de Classe', nex: '50%', pe: '—',
    desc: 'Em NEX 50%, escolhe entre um poder de Ocultista ou o 1º poder de outra trilha de Ocultista.' },
  { nome: 'Escolhido pelo Outro Lado', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '5%', pe: '—',
    desc: 'Lança rituais de 1º círculo. Ganha o 2º círculo em NEX 25%, o 3º em 55% e o 4º em 85%. Começa com três rituais de 1º círculo e, a cada avanço de NEX, aprende um de qualquer círculo que possa lançar, sem contar no limite de rituais conhecidos.' },
  { nome: 'Camuflar Ocultismo', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '2 PE',
    desc: 'Ação livre para esconder símbolos e sigilos, invisíveis a todos menos a você. Ao lançar ritual, +2 PE para lançar sem componentes e sem gesticular. Outros só percebem com Ocultismo (DT 25).' },
  { nome: 'Criar Selo', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: 'variável',
    desc: 'Fabrica selos de rituais que conheça. Gasta uma ação de interlúdio e PE iguais ao custo do ritual. Máximo de selos ao mesmo tempo igual à Presença.' },
  { nome: 'Envolto em Mistério', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: '+5 em Enganação e Intimidação contra pessoas não treinadas em Ocultismo (regra geral, o mestre define).' },
  { nome: 'Especialista em Elemento', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Escolhe um elemento, e a DT para resistir aos seus rituais dele aumenta em +2.' },
  { nome: 'Ferramentas Paranormais', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Reduz em I a categoria de um item paranormal e ativa itens paranormais sem pagar PE.' },
  { nome: 'Fluxo de Poder', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '60%', pe: '—',
    desc: 'Mantém dois efeitos sustentados de rituais com uma ação livre, pagando cada custo. Pré: NEX 60%.' },
  { nome: 'Guiado pelo Paranormal', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '2 PE',
    desc: '1x por cena, 2 PE para uma ação de investigação adicional.' },
  { nome: 'Identificação Paranormal', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: '+10 em Ocultismo para identificar criaturas, objetos ou rituais.' },
  { nome: 'Improvisar Componentes', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: '1x por cena, ação completa e teste de Investigação (DT 15) para achar componentes de um elemento.' },
  { nome: 'Intuição Paranormal', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Ao facilitar investigação, soma Int ou Presença no teste.' },
  { nome: 'Mestre em Elemento', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '45%', pe: '—',
    desc: '–1 PE no custo dos rituais do elemento. Pré: Especialista em Elemento nele, NEX 45%.' },
  { nome: 'Ritual Potente', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Soma Int no dano ou na cura dos rituais. Pré: Int 2.' },
  { nome: 'Ritual Predileto', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: '–1 PE no custo de um ritual que conheça, acumulando com outras reduções.' },
  { nome: 'Tatuagem Ritualística', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: '–1 PE no custo de rituais de alcance pessoal que têm você como alvo.' },
  { nome: 'Transcender', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Escolhe um poder paranormal, mas não ganha Sanidade nesse aumento de NEX. Pode repetir.' },
  { nome: 'Treinamento em Perícia', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', pe: '—',
    desc: 'Treina 2 perícias. A partir de NEX 35% pode subir para veterano e, a partir de 70%, para expert. Pode repetir.' }
];

const HABILIDADES_CATEGORIAS = {
  'Combatente': ["Habilidades de Classe", "Poderes de Combatente", "Aniquilador", "Comandante de Campo", "Guerreiro", "Operações Especiais", "Tropa de Choque"],
  'Especialista': ["Habilidades de Classe", "Poderes de Especialista", "Atirador de Elite", "Infiltrador", "Médico de Campo", "Negociador", "Técnico"],
  'Ocultista': ["Habilidades de Classe", "Poderes de Ocultista", "Conduíte", "Flagelador", "Graduado", "Intuitivo", "Lâmina Paranormal"],
  'Poderes Paranormais': ["Conhecimento", "Energia", "Morte", "Sangue", "Varia"]
};
