// Catálogo de Habilidades — Ordem Paranormal RPG (resumos públicos)
const HABILIDADES_CATALOG = [
  { nome: 'Ataque Especial', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '5%', desc: 'Quando faz um ataque, gaste 2 PE para +5 no teste de ataque ou no dano. Com NEX maior, +1 PE por cada +5 adicional.' },
  { nome: 'Armamento Pesado', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Proficiência com armas pesadas. Pré-requisito: For 2.' },
  { nome: 'Artista Marcial', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Ataques desarmados: 1d6 letal e ágeis. NEX 35%: 1d8. NEX 70%: 1d10.' },
  { nome: 'Ataque de Oportunidade', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Quando um ser sai de espaço adjacente, gaste reação + 1 PE para atacar corpo a corpo.' },
  { nome: 'Combater com Duas Armas', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Com duas armas (uma leve), ao agredir pode fazer ataque adicional com a outra arma.' },
  { nome: 'Combate Defensivo', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Postura defensiva: bônus em Defesa com penalidade em ataques.' },
  { nome: 'Golpe Demolidor', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Ao acertar corpo a corpo, pode empurrar ou derrubar o alvo.' },
  { nome: 'Golpe Pesado', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Ataques corpo a corpo causam dano adicional.' },
  { nome: 'Incansável', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Ignora certas penalidades de fadiga; recupera melhor em interlúdios.' },
  { nome: 'Presteza Atlética', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Bônus em Atletismo e situações de força/agilidade em combate.' },
  { nome: 'Proteção Pesada', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Proficiência com proteções pesadas.' },
  { nome: 'Reflexos Defensivos', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Bônus em Esquiva / reação defensiva.' },
  { nome: 'Saque Rápido', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Sacar ou guardar arma como ação livre (limites conforme livro).' },
  { nome: 'Segurar o Gatilho', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Com armas de fogo, prepare disparo para bônus ou reação.' },
  { nome: 'Sentidos Táticos', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Bônus em Percepção e iniciativa; dificulta ser surpreendido.' },
  { nome: 'Tanque de Guerra', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Mais resistência a dano / PV em combate prolongado.' },
  { nome: 'Tiro Certeiro', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Bônus em ataques à distância contra cobertura ou condições adversas.' },
  { nome: 'Tiro de Cobertura', classe: 'Combatente', categoria: 'Poderes de Combatente', nex: '', desc: 'Usa cobertura de forma eficiente ao atirar.' },
  { nome: 'A Favorita', classe: 'Combatente', categoria: 'Aniquilador', nex: '10%', desc: 'Escolha uma arma favorita; categoria reduzida em I.' },
  { nome: 'Técnica Secreta', classe: 'Combatente', categoria: 'Aniquilador', nex: '40%', desc: 'Categoria da favorita -II. Gaste 2 PE no ataque para efeitos (Amplo, Destruidor); +2 PE por efeito extra.' },
  { nome: 'Técnica Sublime', classe: 'Combatente', categoria: 'Aniquilador', nex: '65%', desc: 'Novos efeitos: Letal (+2 margem) e Perfurante (ignora RD 5).' },
  { nome: 'Máquina de Matar', classe: 'Combatente', categoria: 'Aniquilador', nex: '99%', desc: 'Favorita -III, +2 margem de ameaça e +1 dado de dano do mesmo tipo.' },
  { nome: 'Inspirar Confiança', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '10%', desc: 'Inspira aliado: rerrolagem ou bônus temporário.' },
  { nome: 'Estrategista', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '40%', desc: 'Gaste PE para conceder ação de movimento extra a aliados.' },
  { nome: 'Campo Protetor', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '65%', desc: 'Aliados próximos recebem bônus em Defesa/resistência.' },
  { nome: 'Oficial Comandante', classe: 'Combatente', categoria: 'Comandante de Campo', nex: '99%', desc: 'Ação padrão + 5 PE: aliados em alcance médio recebem ação padrão extra no próximo turno.' },
  { nome: 'Técnica Letal', classe: 'Combatente', categoria: 'Guerreiro', nex: '10%', desc: '+2 na margem de ameaça em ataques corpo a corpo.' },
  { nome: 'Retaliar', classe: 'Combatente', categoria: 'Guerreiro', nex: '40%', desc: 'Ao bloquear, pode contra-atacar.' },
  { nome: 'Potência Bruta', classe: 'Combatente', categoria: 'Guerreiro', nex: '65%', desc: 'Golpes corpo a corpo com dano extra / ignoram parte da RD.' },
  { nome: 'Potência Máxima', classe: 'Combatente', categoria: 'Guerreiro', nex: '99%', desc: 'Ataque Especial corpo a corpo dobra bônus numéricos.' },
  { nome: 'Iniciativa Tática', classe: 'Combatente', categoria: 'Operações Especiais', nex: '10%', desc: 'Bônus em Iniciativa e no primeiro turno.' },
  { nome: 'Movimento Tático', classe: 'Combatente', categoria: 'Operações Especiais', nex: '40%', desc: 'Movimento sem provocar ataques de oportunidade / movimento extra.' },
  { nome: 'Ação Extraordinária', classe: 'Combatente', categoria: 'Operações Especiais', nex: '65%', desc: '1x/rodada: 5 PE para ação padrão ou movimento adicional.' },
  { nome: 'Sempre Alerta', classe: 'Combatente', categoria: 'Operações Especiais', nex: '99%', desc: 'Ação padrão adicional no início de cada cena de combate.' },
  { nome: 'Casca Grossa', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '10%', desc: '+1 PV por 5% de NEX; bloqueio com resistência extra.' },
  { nome: 'Muralha', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '40%', desc: 'Bônus em Defesa; protege aliados adjacentes.' },
  { nome: 'Inquebrável', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '65%', desc: 'Mais RD; resiste melhor a condições.' },
  { nome: 'Último Homem de Pé', classe: 'Combatente', categoria: 'Tropa de Choque', nex: '99%', desc: '+5 Defesa e RD; pode lutar enquanto estiver morrendo.' },
  { nome: 'Eclético', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '5%', desc: 'Habilidade base de versatilidade em perícias.' },
  { nome: 'Perito', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '5%', desc: 'Gaste PE para adicionar dado de bônus em teste de perícia (escala com NEX).' },
  { nome: 'Artista Marcial', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', desc: 'Desarmado 1d6 letal/ágil; 1d8 em 35%; 1d10 em 70%.' },
  { nome: 'Balística Avançada', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', desc: 'Proficiência com armas táticas de fogo e +2 no dano de armas de fogo.' },
  { nome: 'Conhecimento Aplicado', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', desc: '2 PE: usa Intelecto como atributo-base da perícia (exceto Luta/Pontaria). Pré: Int 2.' },
  { nome: 'Hacker', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '', desc: '+5 em Tecnologia (sistemas e redes).' },
  { nome: 'Engenhosidade', classe: 'Especialista', categoria: 'Poderes de Especialista', nex: '40%', desc: 'Aprimora uso de perícias e ferramentas.' },
  { nome: 'Tiro Preciso', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '10%', desc: 'Bônus em Pontaria e dano com armas de precisão.' },
  { nome: 'Disparo Fatal', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '40%', desc: '1x/cena: crítico ou ataque preparado com dano massivo.' },
  { nome: 'Olho de Águia', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '65%', desc: 'Ignora cobertura parcial; bônus em Percepção à distância.' },
  { nome: 'Assassino de Elite', classe: 'Especialista', categoria: 'Atirador de Elite', nex: '99%', desc: 'Ataques de elite podem deixar alvo Morrendo em condições específicas.' },
  { nome: 'Primeiros Socorros Avançados', classe: 'Especialista', categoria: 'Médico de Campo', nex: '10%', desc: 'Cura mais eficiente com Medicina; estabiliza aliados com facilidade.' },
  { nome: 'Cirurgia de Campo', classe: 'Especialista', categoria: 'Médico de Campo', nex: '40%', desc: 'Remove condições graves e recupera PV significativos.' },
  { nome: 'Antídoto Rápido', classe: 'Especialista', categoria: 'Médico de Campo', nex: '65%', desc: 'Trata venenos e doenças paranormais com mais eficácia.' },
  { nome: 'Milagre Médico', classe: 'Especialista', categoria: 'Médico de Campo', nex: '99%', desc: '1x/cena: traz aliado de Morrendo para consciente com PV.' },
  { nome: 'Escolhido pelo Outro Lado', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '5%', desc: 'Conhece rituais de 1º círculo e se conecta a um elemento.' },
  { nome: 'Camuflar Ocultismo', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', desc: 'Ação livre: esconde símbolos/sigilos. +2 PE ao lançar ritual para dificultar identificação.' },
  { nome: 'Especialista em Elemento', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', desc: 'Escolha um elemento: DT dos seus rituais desse elemento +2.' },
  { nome: 'Ferramentas Paranormais', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', desc: 'Catalisadores e componentes mais eficientes.' },
  { nome: 'Presença Inquietante', classe: 'Ocultista', categoria: 'Poderes de Ocultista', nex: '', desc: '+5 em Enganação e Intimidação vs não treinados em Ocultismo.' },
  { nome: 'Ampliar Ritual', classe: 'Ocultista', categoria: 'Conduíte', nex: '10%', desc: '+2 PE: aumenta alcance em um passo ou dobra área do ritual.' },
  { nome: 'Acelerar Ritual', classe: 'Ocultista', categoria: 'Conduíte', nex: '40%', desc: '1x/rodada: reduz tempo de execução do ritual.' },
  { nome: 'Interferir Ritual', classe: 'Ocultista', categoria: 'Conduíte', nex: '65%', desc: 'Pode interromper ou alterar rituais de outros em alcance.' },
  { nome: 'Mestre dos Rituais', classe: 'Ocultista', categoria: 'Conduíte', nex: '99%', desc: 'Alcance/área amplos; conjuração em condições extremas.' },
  { nome: 'Lâmina Maldita', classe: 'Ocultista', categoria: 'Lâmina Paranormal', nex: '10%', desc: 'Aprende Amaldiçoar Arma; pode atacar com Ocultismo na arma amaldiçoada.' },
  { nome: 'Gladiador Paranormal', classe: 'Ocultista', categoria: 'Lâmina Paranormal', nex: '40%', desc: 'Ao acertar corpo a corpo, recebe 2 PE temporários (limite por cena).' },
  { nome: 'Conjuração Marcial', classe: 'Ocultista', categoria: 'Lâmina Paranormal', nex: '65%', desc: '1x/rodada: ao lançar ritual padrão, 2 PE para ataque corpo a corpo livre.' },
  { nome: 'Lâmina do Medo', classe: 'Ocultista', categoria: 'Lâmina Paranormal', nex: '99%', desc: 'Aprende ritual Lâmina do Medo (pode deixar alvo Morrendo).' },
  { nome: 'Flagelo Interior', classe: 'Ocultista', categoria: 'Flagelador', nex: '10%', desc: 'Canaliza dor em poder (PV/SAN por bônus em rituais).' },
  { nome: 'Sacrifício Controlado', classe: 'Ocultista', categoria: 'Flagelador', nex: '40%', desc: 'Converte dano sofrido em bônus para a próxima conjuração.' },
  { nome: 'Martírio Útil', classe: 'Ocultista', categoria: 'Flagelador', nex: '65%', desc: 'Autoflagelo concede PE ou amplia DT de rituais.' },
  { nome: 'Sangue do Outro Lado', classe: 'Ocultista', categoria: 'Flagelador', nex: '99%', desc: 'Sacrifício supremo: rituais poderosos a alto custo.' },
  { nome: 'Estudante Avançado', classe: 'Ocultista', categoria: 'Graduado', nex: '10%', desc: 'Aprende rituais adicionais ou reduz requisitos de círculo.' },
  { nome: 'Tese Ocultista', classe: 'Ocultista', categoria: 'Graduado', nex: '40%', desc: 'Especialização: bônus em DT ou redução de PE em um tipo de ritual.' },
  { nome: 'Doutorado do Medo', classe: 'Ocultista', categoria: 'Graduado', nex: '65%', desc: 'Improvisa efeitos rituais menores com conhecimento profundo.' },
  { nome: 'Arquimago da Ordem', classe: 'Ocultista', categoria: 'Graduado', nex: '99%', desc: 'Máximo domínio: mais rituais e conjuração otimizada.' },
  { nome: 'Intuição Paranormal', classe: 'Ocultista', categoria: 'Intuitivo', nex: '10%', desc: 'Percebe manifestações paranormais com mais facilidade.' },
  { nome: 'Presságio', classe: 'Ocultista', categoria: 'Intuitivo', nex: '40%', desc: '1x/cena: visão ou vantagem em teste crucial.' },
  { nome: 'Sintonizar Entidade', classe: 'Ocultista', categoria: 'Intuitivo', nex: '65%', desc: 'Conecta-se temporariamente a uma entidade para bônus de elemento.' },
  { nome: 'Voz do Outro Lado', classe: 'Ocultista', categoria: 'Intuitivo', nex: '99%', desc: 'Intuição quase infalível para detectar o paranormal.' },
  { nome: 'Parabellum', classe: 'Origens', categoria: 'Origens', nex: '', desc: 'Origem Militar: +2 de dano com armas de fogo (conforme texto).' },
  { nome: 'Motor de Busca', classe: 'Origens', categoria: 'Origens', nex: '', desc: 'Origem T.I.: bônus em Tecnologia e investigação digital.' },
  { nome: 'Ferramenta de Trabalho', classe: 'Origens', categoria: 'Origens', nex: '', desc: 'Origem Operário: bônus com ferramentas e perícias manuais.' },
  { nome: 'Aprender Ritual', classe: 'Poderes Paranormais', categoria: 'Poderes Paranormais', nex: '', desc: 'Aprende um ritual de 1º círculo (áreas maiores em NEX alto). Pode substituir um conhecido.' },
  { nome: 'Resistir a Elemento', classe: 'Poderes Paranormais', categoria: 'Poderes Paranormais', nex: '', desc: 'Resistência 10 a um elemento (Afinidade: 20).' },
  { nome: 'Afortunado', classe: 'Poderes Paranormais', categoria: 'Poderes Paranormais', nex: '', desc: '1x por rolagem: rerrola resultado 1 (exceto d20). Afinidade: também em d20.' }
];

const HABILIDADES_CATEGORIAS = {
  'Combatente': ['Poderes de Combatente', 'Aniquilador', 'Comandante de Campo', 'Guerreiro', 'Operações Especiais', 'Tropa de Choque'],
  'Especialista': ['Poderes de Especialista', 'Atirador de Elite', 'Médico de Campo'],
  'Ocultista': ['Poderes de Ocultista', 'Conduíte', 'Lâmina Paranormal', 'Flagelador', 'Graduado', 'Intuitivo'],
  'Origens': ['Origens'],
  'Poderes Paranormais': ['Poderes Paranormais']
};
