/* Catálogo oficial de equipamentos — Ordem Paranormal RPG 1ª edição */
const ITENS_CATALOG = [
  /* ===== ARMAS SIMPLES ===== */
  { nome: 'Coronhada', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 0, dano: '1d4/1d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Golpe com a coronha da arma de fogo. 1d4 (uma mão) ou 1d6 (duas mãos), crítico x2, impacto. Não ocupa espaço próprio.' },
  { nome: 'Faca', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d4', critico: 19, multiplicador: 2, alcance: 'Curto', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Lâmina afiada (navalha, faca militar ou de churrasco). Arma ágil (usa Agilidade) e pode ser arremessada (alcance curto). Dano 1d4, crítico 19, corte, 1 espaço, categoria 0.' },
  { nome: 'Martelo', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Martelo comum de ferramenta. Dano 1d6, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Punhal', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d4', critico: 20, multiplicador: 3, alcance: '—', tipoDano: 'Perfurante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Adaga ou punhal. Arma ágil (usa Agilidade). Dano 1d4, crítico x3, perfuração, 1 espaço, categoria 0.' },
  { nome: 'Bastão', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6/1d8', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Cilindro de madeira (cassetete, taco, tonfa). Uma mão 1d6 ou duas mãos 1d8, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Machete', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Lâmina longa e larga. Dano 1d6, crítico 19, corte, 1 espaço, categoria 0.' },
  { nome: 'Lança', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6', critico: 20, multiplicador: 2, alcance: 'Curto', tipoDano: 'Perfurante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Haste com ponta metálica. Pode ser arremessada (alcance curto). Dano 1d6, crítico x2, perfuração, 1 espaço, categoria 0.' },
  { nome: 'Cajado', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 2, dano: '1d6/1d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Cabo de madeira ou barra longa. Arma ágil (usa Agilidade); pode ser usada com Combater com Duas Armas. Dano 1d6/1d6, crítico x2, impacto, 2 espaços, categoria 0.' },
  { nome: 'Arco', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 2, dano: '1d6', critico: 20, multiplicador: 3, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arco simples. Consome flechas. Dano 1d6, crítico x3, alcance médio, perfuração, 2 espaços, categoria 0.' },
  { nome: 'Besta', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 2, dano: '1d8', critico: 19, multiplicador: 2, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Besta de mão. Recarregar gasta ação de movimento a cada disparo. Consome flechas. Dano 1d8, crítico 19, alcance médio, perfuração, 2 espaços, categoria 0.' },
  { nome: 'Pistola', tipo: 'arma', grupo: 'Armas Simples', categoria: 'I', espacos: 1, dano: '1d12', critico: 18, multiplicador: 2, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma de fogo curta. Consome balas curtas. Dano 1d12, crítico 18, alcance curto, balístico, 1 espaço, categoria I.' },
  { nome: 'Revólver', tipo: 'arma', grupo: 'Armas Simples', categoria: 'I', espacos: 1, dano: '2d6', critico: 19, multiplicador: 3, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma de fogo de tambor. Consome balas curtas. Dano 2d6, crítico 19/x3, alcance curto, balístico, 1 espaço, categoria I.' },
  { nome: 'Fuzil de Caça', tipo: 'arma', grupo: 'Armas Simples', categoria: 'I', espacos: 2, dano: '2d8', critico: 19, multiplicador: 3, alcance: 'Médio', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Fuzil civil. Consome balas longas. Dano 2d8, crítico 19/x3, alcance médio, balístico, 2 espaços, categoria I.' },

  /* ===== ARMAS TÁTICAS ===== */
  { nome: 'Machadinha', tipo: 'arma', grupo: 'Armas Táticas', categoria: '0', espacos: 1, dano: '1d6', critico: 20, multiplicador: 3, alcance: 'Curto', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Machado pequeno. Pode ser arremessada (alcance curto). Dano 1d6, crítico x3, corte, 1 espaço, categoria 0.' },
  { nome: 'Nunchaku', tipo: 'arma', grupo: 'Armas Táticas', categoria: '0', espacos: 1, dano: '1d8', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Arma ágil (usa Agilidade). Dano 1d8, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Corrente', tipo: 'arma', grupo: 'Armas Táticas', categoria: '0', espacos: 1, dano: '1d8', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: '+2 em testes de desarmar/derrubar. Dano 1d8, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Espada', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '1d8/1d10', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Uma mão 1d8 ou duas mãos 1d10, crítico 19, corte, 1 espaço, categoria I.' },
  { nome: 'Florete', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '1d6', critico: 18, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Arma ágil (usa Agilidade). Dano 1d6, crítico 18, corte, 1 espaço, categoria I.' },
  { nome: 'Machado', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '1d8', critico: 20, multiplicador: 3, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 1d8, crítico x3, corte, 1 espaço, categoria I.' },
  { nome: 'Maça', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '2d4', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 2d4, crítico x2, impacto, 1 espaço, categoria I.' },
  { nome: 'Acha', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d12', critico: 20, multiplicador: 3, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 1d12, crítico x3, corte, 2 espaços, categoria I.' },
  { nome: 'Gadanho', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '2d4', critico: 20, multiplicador: 4, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 2d4, crítico x4, corte, 2 espaços, categoria I.' },
  { nome: 'Katana', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d10', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Arma ágil se você for veterano em Luta. Dano 1d10, crítico 19, corte, 2 espaços, categoria I.' },
  { nome: 'Marreta', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '3d4', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 3d4, crítico x2, impacto, 2 espaços, categoria I.' },
  { nome: 'Montante', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '2d6', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 2d6, crítico 19, corte, 2 espaços, categoria I.' },
  { nome: 'Motosserra', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '3d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Rolar 6 num dado de dano soma um dado extra; –O no ataque; ligar gasta ação de movimento. Dano 3d6, crítico x2, corte, 2 espaços, categoria I.' },
  { nome: 'Arco Composto', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d10', critico: 20, multiplicador: 3, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Aplica Força no dano (diferente de outras armas de disparo). Consome flechas. Dano 1d10, crítico x3, alcance médio, 2 espaços, categoria I.' },
  { nome: 'Balestra', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d12', critico: 19, multiplicador: 2, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Recarregar gasta ação de movimento a cada disparo. Consome flechas. Dano 1d12, crítico 19, alcance médio, 2 espaços, categoria I.' },
  { nome: 'Submetralhadora', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '2d6', critico: 19, multiplicador: 3, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma automática: rajada dá –O no ataque mas +1 dado de dano do mesmo tipo. Consome balas curtas. Dano 2d6, crítico 19/x3, alcance curto, 1 espaço, categoria I.' },
  { nome: 'Espingarda', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '4d6', critico: 20, multiplicador: 3, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Metade do dano em alcance médio ou maior. Consome cartuchos. Dano 4d6, crítico x3, alcance curto, 2 espaços, categoria I.' },
  { nome: 'Fuzil de Assalto', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'II', espacos: 2, dano: '2d10', critico: 19, multiplicador: 3, alcance: 'Médio', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma automática: rajada dá –O no ataque mas +1 dado de dano. Consome balas longas. Dano 2d10, crítico 19/x3, alcance médio, 2 espaços, categoria II.' },
  { nome: 'Fuzil de Precisão', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'III', espacos: 2, dano: '2d10', critico: 19, multiplicador: 3, alcance: 'Longo', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Se veterano em Pontaria e mirar com ele, +5 na margem de ameaça. Consome balas longas. Dano 2d10, crítico 19/x3, alcance longo, 2 espaços, categoria III.' },
  { nome: 'Bazuca', tipo: 'arma', grupo: 'Armas Pesadas', categoria: 'III', espacos: 2, dano: '10d8', critico: 20, multiplicador: 2, alcance: 'Médio', tipoDano: 'Impacto', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Atinge o alvo + todos num raio de 3 m (Reflexos DT Agi reduz à metade, exceto o alvo direto); pode disparar num ponto vazio (sem teste de ataque); recarregar gasta ação de movimento. Consome foguete. Dano 10d8, crítico x2, 2 espaços, categoria III.' },
  { nome: 'Lança-chamas', tipo: 'arma', grupo: 'Armas Pesadas', categoria: 'III', espacos: 2, dano: '6d6', critico: 20, multiplicador: 2, alcance: 'Curto', tipoDano: 'Fogo', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Atinge todos numa linha de 1,5 m de largura a alcance curto (1 teste de ataque vs Defesa de todos); atingidos também ficam em chamas. Consome combustível. Dano 6d6 fogo, crítico x2, 2 espaços, categoria III.' },
  { nome: 'Metralhadora', tipo: 'arma', grupo: 'Armas Pesadas', categoria: 'II', espacos: 2, dano: '2d12', critico: 19, multiplicador: 3, alcance: 'Médio', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Precisa Força 4+ ou ação de movimento para apoiar em tripé, senão –5 no ataque; é automática (rajada: –O no ataque, +1 dado de dano). Consome balas longas. Dano 2d12, crítico 19/x3, alcance médio, 2 espaços, categoria II.' },

  /* ===== MUNIÇÃO ===== */
  { nome: 'Flechas', tipo: 'municao', grupo: 'Munição', categoria: '0', espacos: 1,
    desc: 'Pacote de flechas/virotes. Duração: 1 missão inteira. 1 espaço, categoria 0.' },
  { nome: 'Balas Curtas', tipo: 'municao', grupo: 'Munição', categoria: '0', espacos: 1,
    desc: 'Munição para pistola, revólver e submetralhadora. Duração do pacote: 2 cenas. 1 espaço, categoria 0.' },
  { nome: 'Balas Longas', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Munição para fuzis e metralhadora. Duração do pacote: 1 cena. 1 espaço, categoria I.' },
  { nome: 'Cartuchos', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Munição para espingarda. Duração do pacote: 1 cena. 1 espaço, categoria I.' },
  { nome: 'Foguete', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Para bazuca. Duração: 1 disparo. 1 espaço, categoria I.' },
  { nome: 'Combustível', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Para lança-chamas. Duração do pacote: 1 cena. 1 espaço, categoria I.' },
  { nome: 'Dardos extras', tipo: 'municao', grupo: 'Munição', categoria: '0', espacos: 1,
    desc: 'Caixa com 2 dardos extras para pistola de dardos. Categoria 0, 1 espaço.' },
  { nome: 'Cargas de sinalizador', tipo: 'municao', grupo: 'Munição', categoria: '0', espacos: 1,
    desc: 'Caixa com 2 cargas extras para pistola sinalizadora. Categoria 0, 1 espaço.' },

  /* ===== PROTEÇÕES ===== */
  { nome: 'Proteção Leve', tipo: 'protecao', grupo: 'Proteções', categoria: 'I', espacos: 2, defesa: 5,
    desc: 'Defesa +5, categoria I, 2 espaços. Sem proficiência: –OO em testes baseados em Força e Agilidade.' },
  { nome: 'Proteção Pesada', tipo: 'protecao', grupo: 'Proteções', categoria: 'II', espacos: 5, defesa: 10,
    desc: 'Defesa +10, categoria II, 5 espaços. RD 2 contra balístico/corte/impacto/perfuração; –5 em perícias com penalidade de carga. Sem proficiência: –OO em testes de Força e Agilidade.' },
  { nome: 'Escudo', tipo: 'protecao', grupo: 'Proteções', categoria: 'I', espacos: 2, defesa: 2,
    desc: 'Defesa +2, categoria I, 2 espaços. Precisa ser empunhado numa mão; soma com a Defesa de outra proteção; conta como pesada para fins de proficiência.' },
  { nome: 'Proteção Leve Discreta', tipo: 'protecao', grupo: 'Proteções', categoria: 'II', espacos: 1, defesa: 5,
    desc: 'Proteção leve com modificação Discreta: kevlar denso.\nDefesa +5, categoria II (I+I), 1 espaço.\n+5 em testes de Crime para ocultá-la (pode testar sem treino). Só em proteções leves.' },
  { nome: 'Proteção Leve Reforçada', tipo: 'protecao', grupo: 'Proteções', categoria: 'II', espacos: 3, defesa: 7,
    desc: 'Proteção leve com modificação Reforçada.\nDefesa +7, categoria II, 3 espaços. Não pode ser discreta e reforçada ao mesmo tempo.' },
  { nome: 'Proteção Pesada Antibombas', tipo: 'protecao', grupo: 'Proteções', categoria: 'III', espacos: 5, defesa: 10,
    desc: 'Proteção pesada com Antibombas: +5 em testes de resistência contra efeitos de área.\nDefesa +10, RD 2, categoria III, 5 espaços. Só em proteções pesadas.' },
  { nome: 'Proteção Pesada Blindada', tipo: 'protecao', grupo: 'Proteções', categoria: 'III', espacos: 6, defesa: 10,
    desc: 'Proteção pesada com Blindada: placas de aço e cerâmica.\nDefesa +10, RD 5, categoria III, 6 espaços.' },
  { nome: 'Proteção Pesada Reforçada', tipo: 'protecao', grupo: 'Proteções', categoria: 'III', espacos: 6, defesa: 12,
    desc: 'Proteção pesada com Reforçada.\nDefesa +12, RD 2, categoria III, 6 espaços.' },

  /* ===== ACESSÓRIOS ===== */
  { nome: 'Kit de Perícia', tipo: 'geral', grupo: 'Acessórios', categoria: '0', espacos: 1,
    desc: 'Categoria 0, 1 espaço. Necessário para certas perícias/usos (sem ele: –5 no teste).' },
  { nome: 'Utensílio', tipo: 'geral', grupo: 'Acessórios', categoria: 'I', espacos: 1,
    desc: 'Item comum com utilidade específica (canivete, lupa, smartphone, notebook…). Fornece +2 em uma perícia (exceto Luta e Pontaria). Precisa ser empunhado. 1 espaço, categoria I. O mestre aprova o utensílio.' },
  { nome: 'Vestimenta', tipo: 'geral', grupo: 'Acessórios', categoria: 'I', espacos: 1,
    desc: 'Peça de vestuário que fornece +2 em uma perícia (exceto Luta ou Pontaria). Máximo de duas vestimentas ao mesmo tempo. Vestir/despir: ação completa. 1 espaço, categoria I.' },

  /* ===== EXPLOSIVOS ===== */
  { nome: 'Granada de Atordoamento', tipo: 'geral', grupo: 'Explosivos', categoria: '0', espacos: 1,
    desc: 'Categoria 0, 1 espaço. Raio 6 m: atordoado 1 rodada (Fortitude DT Agi reduz para ofuscado+surdo 1 rodada). Arremessar: empunhar + ação padrão, alcance médio.' },
  { nome: 'Granada de Fragmentação', tipo: 'geral', grupo: 'Explosivos', categoria: 'I', espacos: 1,
    desc: 'Categoria I, 1 espaço. Raio 6 m: 8d6 perfuração (Reflexos DT Agi reduz à metade).' },
  { nome: 'Granada de Fumaça', tipo: 'geral', grupo: 'Explosivos', categoria: '0', espacos: 1,
    desc: 'Categoria 0, 1 espaço. Raio 6 m: cego + camuflagem total por 2 rodadas.' },
  { nome: 'Granada Incendiária', tipo: 'geral', grupo: 'Explosivos', categoria: 'I', espacos: 1,
    desc: 'Categoria I, 1 espaço. Raio 6 m: 6d6 fogo + em chamas (Reflexos DT Agi reduz dano à metade e evita a condição).' },
  { nome: 'Mina Antipessoal', tipo: 'geral', grupo: 'Explosivos', categoria: 'I', espacos: 1,
    desc: 'Instalar: ação completa e Tática DT 15 (se falhar, gasta a mina). Detonar: ação padrão a até alcance longo.\nCone de 6 m, 12d6 de perfuração (Reflexos DT Int reduz à metade). Encontrar: Percepção (DT = seu teste de instalação). Categoria I, 1 espaço.' },

  /* ===== ITENS OPERACIONAIS ===== */
  { nome: 'Algemas', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: 'Categoria 0, 1 espaço. Prende alguém não indefeso (empunhar + agarrar + vencer novo teste de agarrar); –5 em ações com as mãos, impede conjurar; escapar exige Acrobacia DT 30.' },
  { nome: 'Arpéu', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: 'Gancho para amarrar na ponta de uma corda. Prender: Pontaria DT 15. Subir um muro com corda: +5 em Atletismo. Categoria 0, 1 espaço.' },
  { nome: 'Bandoleira', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Cinto com bolsos e alças. Uma vez por rodada, sacar ou guardar um item do inventário como ação livre. Categoria I, 1 espaço.' },
  { nome: 'Binóculos', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: 'Binóculos militares: +5 em testes de Percepção para observar coisas distantes. Categoria 0, 1 espaço.' },
  { nome: 'Bloqueador de Sinal', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Emite interferência: nenhum celular em alcance médio consegue se conectar. Categoria I, 1 espaço.' },
  { nome: 'Cicatrizante', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Categoria I, 1 espaço. Ação padrão cura 2d8+2 PV em si ou adjacente.' },
  { nome: 'Corda', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: 'Rolo de 10 m. +5 em Atletismo para descer buracos/prédios; amarrar inconscientes etc. Categoria 0, 1 espaço.' },
  { nome: 'Equipamento de Sobrevivência', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 2,
    desc: 'Saco de dormir, panelas, GPS e afins. +5 em Sobrevivência para acampar e orientar-se, e permite esses testes sem treinamento. Categoria 0, 2 espaços.' },
  { nome: 'Lanterna Tática', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Ilumina um cone de 9 m. Ação de movimento: mirar nos olhos de um ser em alcance curto — ele fica ofuscado por 1 rodada, mas imune à lanterna pelo resto da cena. Categoria I, 1 espaço.' },
  { nome: 'Máscara de Gás', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: '+10 em testes de Fortitude contra efeitos que dependam de respiração. Categoria 0, 1 espaço.' },
  { nome: 'Mochila Militar', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 0,
    desc: 'Categoria I. Não ocupa espaço; +2 espaços de carga.' },
  { nome: 'Óculos de Visão Térmica', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Eliminam a penalidade em testes por camuflagem. Categoria I, 1 espaço.' },
  { nome: 'Pé de Cabra', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: '+5 em testes de Força para arrombar portas. Em combate, funciona como um bastão. Categoria 0, 1 espaço.' },
  { nome: 'Pistola de Dardos', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1, dano: '—', alcance: 'Curto', pericia: 'Pontaria',
    desc: 'Arma leve, alcance curto. Se acertar, o alvo fica inconsciente até o fim da cena (Fortitude DT Agi reduz para desprevenido e lento por 1 rodada). Vem com 2 dardos. Categoria I, 1 espaço.' },
  { nome: 'Pistola Sinalizadora', tipo: 'arma', grupo: 'Itens Operacionais', categoria: '0', espacos: 1, dano: '2d6', critico: 20, multiplicador: 2, alcance: 'Curto', tipoDano: 'Fogo', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Dispara um sinalizador. Pode ser usada como arma de disparo leve: 2d6 de fogo, alcance curto. Vem com 2 cargas. Categoria 0, 1 espaço.' },
  { nome: 'Soqueira', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: '+1 no dano desarmado e torna esse dano letal. Pode receber modificações e maldições de armas corpo a corpo, aplicadas nos ataques desarmados. Categoria 0, 1 espaço.' },
  { nome: 'Spray de Pimenta', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Ação padrão, ser adjacente: fica cego por 1d4 rodadas (Fortitude DT Agi evita). Dois usos. Categoria I, 1 espaço.' },
  { nome: 'Taser', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Ação padrão, ser adjacente: 1d6 de eletricidade e atordoado por 1 rodada (Fortitude DT Agi evita). Dois usos. Categoria I, 1 espaço.' },
  { nome: 'Traje Hazmat', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 2,
    desc: 'Cobre o corpo inteiro. +5 em testes de resistência contra efeitos ambientais e resistência a químico 10. Categoria I, 2 espaços.' },

  /* ===== ITENS PARANORMAIS / AMALDIÇOADOS ===== */
  { nome: 'Amarras de Sangue', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Cordas/correntes do elemento Sangue, para imobilizar criaturas vulneráveis a Sangue.\nArmadilha: gasta as amarras, ação completa e 2 PE — área 3x3 m. Criatura que entre (1ª vez no turno) faz Reflexos (DT Int); falha = imóvel até o fim da cena; sucesso = terreno difícil.\nLaçar: ação padrão e 1 PE, criatura em alcance curto. Vontade (DT Agi) ou paralisada até o início do próximo turno (pode repetir). Manter: 1 PE por rodada.' },
  { nome: 'Amarras de Morte', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Como Amarras de Sangue, mas do elemento Morte (imobiliza criaturas vulneráveis a Morte).\nArmadilha: ação completa + 2 PE. Laçar: ação padrão + 1 PE, manter 1 PE/rodada.' },
  { nome: 'Amarras de Energia', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Como Amarras de Sangue, mas do elemento Energia.\nArmadilha: ação completa + 2 PE. Laçar: ação padrão + 1 PE, manter 1 PE/rodada.' },
  { nome: 'Amarras de Conhecimento', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Como Amarras de Sangue, mas do elemento Conhecimento.\nArmadilha: ação completa + 2 PE. Laçar: ação padrão + 1 PE, manter 1 PE/rodada.' },
  { nome: 'Câmera de Aura Paranormal', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Câmera amaldiçoada com Energia e sigilos de Conhecimento. Tirar foto: ação padrão e 1 PE. Revela auras paranormais em pessoas e objetos, na cor do elemento.' },
  { nome: 'Componentes Ritualísticos de Energia', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: '0', espacos: 1,
    desc: 'Necessários para conjurar rituais de Energia. Categoria 0, 1 espaço.' },
  { nome: 'Componentes Ritualísticos de Sangue', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: '0', espacos: 1,
    desc: 'Necessários para conjurar rituais de Sangue. Categoria 0, 1 espaço.' },
  { nome: 'Componentes Ritualísticos de Morte', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: '0', espacos: 1,
    desc: 'Necessários para conjurar rituais de Morte. Categoria 0, 1 espaço.' },
  { nome: 'Componentes Ritualísticos de Conhecimento', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: '0', espacos: 1,
    desc: 'Necessários para conjurar rituais de Conhecimento. Não existem componentes de Medo. Categoria 0, 1 espaço.' },
  { nome: 'Emissor de Pulsos Paranormais', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Ação completa + 1 PE emite pulso de um elemento: atrai criaturas do mesmo elemento e afasta do elemento oposto (Vontade DT Pre evita). Categoria II, 1 espaço.' },
  { nome: 'Escuta de Ruídos Paranormais', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Ação completa + 2 PE grava ruídos paranormais por até 24h; ouvir dá +5 em Ocultismo para identificar criatura. Categoria II, 1 espaço.' },
  { nome: 'Medidor de Estabilidade da Membrana', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Treinado em Ocultismo avalia a chance de manifestação numa área (indicativo, não garantido). Categoria II, 1 espaço.' },
  { nome: 'Scanner de Manifestação Paranormal de Sangue', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Ação padrão ativa; custa 1 PE/rodada; sabe a direção de manifestações ativas de Sangue em alcance longo (também detecta criaturas que tenham Sangue como complemento). Categoria II, 1 espaço.' },
  { nome: 'Scanner de Manifestação Paranormal de Morte', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Ação padrão ativa; custa 1 PE/rodada; sabe a direção de manifestações ativas de Morte em alcance longo (também detecta criaturas que tenham Morte como complemento). Categoria II, 1 espaço.' },
  { nome: 'Scanner de Manifestação Paranormal de Energia', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Ação padrão ativa; custa 1 PE/rodada; sabe a direção de manifestações ativas de Energia em alcance longo (também detecta criaturas que tenham Energia como complemento). Categoria II, 1 espaço.' },
  { nome: 'Scanner de Manifestação Paranormal de Conhecimento', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Ação padrão ativa; custa 1 PE/rodada; sabe a direção de manifestações ativas de Conhecimento em alcance longo (também detecta criaturas que tenham Conhecimento como complemento). Categoria II, 1 espaço.' }
];
