/* Catálogo oficial de equipamentos — Ordem Paranormal RPG 1ª edição */
const ITENS_CATALOG = [
  /* ===== ARMAS SIMPLES ===== */
  { nome: 'Faca', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d4', critico: 19, multiplicador: 2, alcance: 'Curto', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Lâmina afiada (navalha, faca militar ou de churrasco). Arma ágil e pode ser arremessada (alcance curto).\nDano 1d4, crítico 19, cortante, 1 espaço, categoria 0.' },
  { nome: 'Martelo', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Martelo comum de ferramenta. Dano 1d6, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Punhal', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d4', critico: 20, multiplicador: 3, alcance: '—', tipoDano: 'Perfurante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Adaga ou punhal. Dano 1d4, crítico x3, perfurante, 1 espaço, categoria 0.' },
  { nome: 'Bastão', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6/1d8', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Cilindro de madeira (cassetete, taco, tonfa). Uma mão 1d6 ou duas mãos 1d8, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Machete', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Lâmina longa e larga, usada para abrir trilhas. Dano 1d6, crítico 19, cortante, 1 espaço, categoria 0.' },
  { nome: 'Lança', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6', critico: 20, multiplicador: 2, alcance: 'Curto', tipoDano: 'Perfurante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Haste com ponta metálica. Pode ser arremessada (alcance curto). Dano 1d6, crítico x2, perfurante, 1 espaço, categoria 0.' },
  { nome: 'Cajado', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 2, dano: '1d6/1d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Cabo de madeira ou barra longa. Arma ágil; pode ser usada com Combater com Duas Armas. Dano 1d6/1d6, crítico x2, impacto, 2 espaços, categoria 0.' },
  { nome: 'Arco', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 2, dano: '1d6', critico: 20, multiplicador: 3, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arco comum. Consome flechas. Dano 1d6, crítico x3, alcance médio, perfurante, 2 espaços, categoria 0.' },
  { nome: 'Besta', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 2, dano: '1d8', critico: 19, multiplicador: 2, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma antiga. Exige ação de movimento para recarregar a cada disparo. Consome flechas/virotes. Dano 1d8, crítico 19, alcance médio, 2 espaços, categoria 0.' },
  { nome: 'Pistola', tipo: 'arma', grupo: 'Armas Simples', categoria: 'I', espacos: 1, dano: '1d12', critico: 18, multiplicador: 2, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma de fogo leve. Consome balas curtas. Dano 1d12, crítico 18, alcance curto, balístico, 1 espaço, categoria I.' },
  { nome: 'Revólver', tipo: 'arma', grupo: 'Armas Simples', categoria: 'I', espacos: 1, dano: '2d6', critico: 19, multiplicador: 3, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma de fogo leve. Consome balas curtas. Dano 2d6, crítico 19/x3, alcance curto, balístico, 1 espaço, categoria I.' },
  { nome: 'Fuzil de Caça', tipo: 'arma', grupo: 'Armas Simples', categoria: 'I', espacos: 2, dano: '2d8', critico: 19, multiplicador: 3, alcance: 'Médio', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma de fogo de duas mãos, comum entre caçadores. Consome balas longas. Dano 2d8, crítico 19/x3, alcance médio, 2 espaços, categoria I.' },

  /* ===== ARMAS TÁTICAS ===== */
  { nome: 'Machadinha', tipo: 'arma', grupo: 'Armas Táticas', categoria: '0', espacos: 1, dano: '1d6', critico: 20, multiplicador: 3, alcance: 'Curto', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Ferramenta de corte. Pode ser arremessada (alcance curto). Dano 1d6, crítico x3, cortante, 1 espaço, categoria 0.' },
  { nome: 'Nunchaku', tipo: 'arma', grupo: 'Armas Táticas', categoria: '0', espacos: 1, dano: '1d8', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Arma de artes marciais. Dano 1d8, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Corrente', tipo: 'arma', grupo: 'Armas Táticas', categoria: '0', espacos: 1, dano: '1d8', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Corrente grossa. Fornece +2 em testes para desarmar e derrubar. Dano 1d8, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Espada', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '1d8/1d10', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Espada longa ou cimitarra. Uma mão 1d8 ou duas mãos 1d10, crítico 19, cortante, 1 espaço, categoria I.' },
  { nome: 'Florete', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '1d6', critico: 18, multiplicador: 2, alcance: '—', tipoDano: 'Perfurante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Espada de lâmina fina. Arma ágil. Dano 1d6, crítico 18, perfurante, 1 espaço, categoria I.' },
  { nome: 'Machado', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '1d8', critico: 20, multiplicador: 3, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Machado de uma mão. Dano 1d8, crítico x3, cortante, 1 espaço, categoria I.' },
  { nome: 'Maça', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '2d4', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Bastão com cabeça metálica. Dano 2d4, crítico x2, impacto, 1 espaço, categoria I.' },
  { nome: 'Acha', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d12', critico: 20, multiplicador: 3, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Machado grande de duas mãos. Dano 1d12, crítico x3, cortante, 2 espaços, categoria I.' },
  { nome: 'Gadanho', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '2d4', critico: 20, multiplicador: 4, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Foice grande de duas mãos. Dano 2d4, crítico x4, cortante, 2 espaços, categoria I.' },
  { nome: 'Katana', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d10', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Espada longa levemente curvada. Arma ágil. Se veterano em Luta, pode ser usada com uma mão. Dano 1d10, crítico 19, cortante, 2 espaços, categoria I.' },
  { nome: 'Marreta', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '3d4', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Marreta de duas mãos. Dano 3d4, crítico x2, impacto, 2 espaços, categoria I.' },
  { nome: 'Montante', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '2d6', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Espada de duas mãos. Dano 2d6, crítico 19, cortante, 2 espaços, categoria I.' },
  { nome: 'Motosserra', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '3d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Serra elétrica de duas mãos. Dano 3d6, crítico x2, cortante, 2 espaços, categoria I.' },
  { nome: 'Arco Composto', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d10', critico: 20, multiplicador: 3, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arco moderno com roldanas. Permite aplicar Força nas rolagens de dano. Consome flechas. Dano 1d10, crítico x3, alcance médio, 2 espaços, categoria I.' },
  { nome: 'Balestra', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d12', critico: 19, multiplicador: 2, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Besta pesada. Exige ação de movimento para recarregar a cada disparo. Consome flechas. Dano 1d12, crítico 19, alcance médio, 2 espaços, categoria I.' },
  { nome: 'Submetralhadora', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '2d6', critico: 19, multiplicador: 3, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma de fogo automática de uma mão. Consome balas curtas. Dano 2d6, crítico 19/x3, alcance curto, 1 espaço, categoria I.' },
  { nome: 'Espingarda', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '4d6', critico: 20, multiplicador: 3, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Cano liso de duas mãos. Causa metade do dano em alcance médio ou maior. Consome cartuchos. Dano 4d6, crítico x3, alcance curto, 2 espaços, categoria I.' },
  { nome: 'Fuzil de Assalto', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'II', espacos: 2, dano: '2d10', critico: 19, multiplicador: 3, alcance: 'Médio', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma de fogo automática padrão de exércitos. Consome balas longas. Dano 2d10, crítico 19/x3, alcance médio, 2 espaços, categoria II.' },
  { nome: 'Fuzil de Precisão', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'III', espacos: 2, dano: '2d10', critico: 19, multiplicador: 3, alcance: 'Longo', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Fuzil militar para disparos longos. Se veterano em Pontaria e gastar a ação mirar, recebe +5 na margem de ameaça. Consome balas longas. Dano 2d10, crítico 19/x3, alcance longo, 2 espaços, categoria III.' },
  { nome: 'Bazuca', tipo: 'arma', grupo: 'Armas Pesadas', categoria: 'III', espacos: 2, dano: '10d8', critico: 20, multiplicador: 2, alcance: 'Médio', tipoDano: 'Impacto', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Lança-foguetes. Dano no alvo e em seres num raio de 3 m (Reflexos reduz à metade). Pode disparar num ponto em alcance médio sem teste de ataque. Recarregar: ação de movimento. Consome foguetes. Dano 10d8, crítico x2, 2 espaços, categoria III.' },
  { nome: 'Lança-chamas', tipo: 'arma', grupo: 'Armas Pesadas', categoria: 'III', espacos: 2, dano: '6d6', critico: 20, multiplicador: 2, alcance: 'Curto', tipoDano: 'Fogo', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Atinge todos em uma linha de 1,5 m de largura e alcance curto. Um único teste de ataque contra a Defesa de cada um. Atingidos ficam em chamas. Consome combustível. Dano 6d6 fogo, crítico x2, 2 espaços, categoria III.' },
  { nome: 'Metralhadora', tipo: 'arma', grupo: 'Armas Pesadas', categoria: 'II', espacos: 2, dano: '2d12', critico: 19, multiplicador: 3, alcance: 'Médio', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma de fogo pesada automática. Consome balas longas. Dano 2d12, crítico 19/x3, alcance médio, 2 espaços, categoria II.' },

  /* ===== MUNIÇÃO ===== */
  { nome: 'Flechas', tipo: 'municao', grupo: 'Munição', categoria: '0', espacos: 1,
    desc: 'Pacote de flechas/virotes para arco, besta, arco composto ou balestra. Ocupa 1 espaço, categoria 0. Ter o pacote no inventário permite usar a arma na cena.' },
  { nome: 'Balas Curtas', tipo: 'municao', grupo: 'Munição', categoria: '0', espacos: 1,
    desc: 'Munição para pistola, revólver e submetralhadora. 1 espaço, categoria 0.' },
  { nome: 'Balas Longas', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Munição para fuzil de caça, fuzil de assalto, fuzil de precisão e metralhadora. 1 espaço, categoria I.' },
  { nome: 'Cartuchos', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Cartuchos para espingarda. 1 espaço, categoria I.' },
  { nome: 'Foguete', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Munição para bazuca. 1 espaço, categoria I.' },
  { nome: 'Combustível', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Combustível para lança-chamas. 1 espaço, categoria I.' },
  { nome: 'Dardos extras', tipo: 'municao', grupo: 'Munição', categoria: '0', espacos: 1,
    desc: 'Caixa com 2 dardos extras para pistola de dardos. Categoria 0, 1 espaço.' },
  { nome: 'Cargas de sinalizador', tipo: 'municao', grupo: 'Munição', categoria: '0', espacos: 1,
    desc: 'Caixa com 2 cargas extras para pistola sinalizadora. Categoria 0, 1 espaço.' },

  /* ===== PROTEÇÕES ===== */
  { nome: 'Proteção Leve', tipo: 'protecao', grupo: 'Proteções', categoria: 'I', espacos: 2, defesa: 5,
    desc: 'Jaqueta de couro pesada ou colete de kevlar, típico de seguranças e policiais.\nDefesa +5, categoria I, 2 espaços.\nSem proficiência: –5 em testes baseados em Força e Agilidade.' },
  { nome: 'Proteção Pesada', tipo: 'protecao', grupo: 'Proteções', categoria: 'II', espacos: 5, defesa: 10,
    desc: 'Capacete, ombreiras, joelheiras, caneleiras e colete com várias camadas de kevlar.\nDefesa +10, categoria II, 5 espaços.\nResistência a balístico, corte, impacto e perfuração 2.\n–5 em testes de perícias que sofrem penalidade de carga.\nSem proficiência: –5 em testes de Força e Agilidade.' },
  { nome: 'Escudo', tipo: 'protecao', grupo: 'Proteções', categoria: 'I', espacos: 2, defesa: 2,
    desc: 'Escudo medieval ou de tropa de choque. Precisa ser empunhado em uma mão.\nDefesa +2 (acumula com proteção). Categoria I, 2 espaços.\nPara proficiência, conta como proteção pesada.' },
  { nome: 'Proteção Leve Discreta', tipo: 'protecao', grupo: 'Proteções', categoria: 'II', espacos: 1, defesa: 5,
    desc: 'Proteção leve com modificação Discreta: kevlar denso.\nDefesa +5, categoria II (I+I), 1 espaço.\n+5 em testes de Crime para ocultá-la (pode testar sem treino). Só em proteções leves.' },
  { nome: 'Proteção Leve Reforçada', tipo: 'protecao', grupo: 'Proteções', categoria: 'II', espacos: 3, defesa: 7,
    desc: 'Proteção leve com modificação Reforçada.\nDefesa +7, categoria II, 3 espaços. Não pode ser discreta e reforçada ao mesmo tempo.' },
  { nome: 'Proteção Pesada Antibombas', tipo: 'protecao', grupo: 'Proteções', categoria: 'III', espacos: 5, defesa: 10,
    desc: 'Proteção pesada com Antibombas: +5 em testes de resistência contra efeitos de área.\nDefesa +10, RD 2, categoria III, 5 espaços. Só em proteções pesadas.' },
  { nome: 'Proteção Pesada Blindada', tipo: 'protecao', grupo: 'Proteções', categoria: 'III', espacos: 6, defesa: 10,
    desc: 'Proteção pesada com Blindada: placas de aço e cerâmica.\nDefesa +10, RD 5, categoria III, 6 espaços.' },
  { nome: 'Proteção Pesada Reforçada', tipo: 'protecao', grupo: 'Proteções', categoria: 'III', espacos: 6, defesa: 12,
    desc: 'Proteção pesada com Reforçada.\nDefesa +12, RD 2, categoria III, 6 espaços.' },

  /* ===== ACESSÓRIOS ===== */
  { nome: 'Kit de Perícia', tipo: 'geral', grupo: 'Acessórios', categoria: '0', espacos: 1,
    desc: 'Ferramentas para uma perícia específica. Sem o kit, você sofre –5 no teste dessa perícia (quando o kit é exigido). Existe um kit para cada perícia que precisa dele. 1 espaço, categoria 0.' },
  { nome: 'Utensílio', tipo: 'geral', grupo: 'Acessórios', categoria: 'I', espacos: 1,
    desc: 'Item comum com utilidade específica (canivete, lupa, smartphone, notebook…). Fornece +2 em uma perícia (exceto Luta e Pontaria). Precisa ser empunhado. 1 espaço, categoria I. O mestre aprova o utensílio.' },
  { nome: 'Vestimenta', tipo: 'geral', grupo: 'Acessórios', categoria: 'I', espacos: 1,
    desc: 'Peça de vestuário que fornece +2 em uma perícia (exceto Luta ou Pontaria). Máximo de duas vestimentas ao mesmo tempo. Vestir/despir: ação completa. 1 espaço, categoria I.' },

  /* ===== EXPLOSIVOS ===== */
  { nome: 'Granada de Atordoamento', tipo: 'geral', grupo: 'Explosivos', categoria: '0', espacos: 1,
    desc: 'Flash-bang. Ação padrão, arremesso em alcance médio, raio de 6 m.\nSeres na área ficam atordoados por 1 rodada (Fortitude DT Agi reduz para ofuscado e surdo por 1 rodada). Categoria 0, 1 espaço.' },
  { nome: 'Granada de Fragmentação', tipo: 'geral', grupo: 'Explosivos', categoria: 'I', espacos: 1,
    desc: 'Ação padrão, arremesso em alcance médio, raio de 6 m.\n8d6 de dano de perfuração (Reflexos DT Agi reduz à metade). Categoria I, 1 espaço.' },
  { nome: 'Granada de Fumaça', tipo: 'geral', grupo: 'Explosivos', categoria: '0', espacos: 1,
    desc: 'Ação padrão, arremesso em alcance médio, raio de 6 m.\nSeres na área ficam cegos e sob camuflagem total. A fumaça dura 2 rodadas. Categoria 0, 1 espaço.' },
  { nome: 'Granada Incendiária', tipo: 'geral', grupo: 'Explosivos', categoria: 'I', espacos: 1,
    desc: 'Ação padrão, arremesso em alcance médio, raio de 6 m.\n6d6 de dano de fogo e em chamas (Reflexos DT Agi reduz o dano à metade e evita em chamas). Categoria I, 1 espaço.' },
  { nome: 'Mina Antipessoal', tipo: 'geral', grupo: 'Explosivos', categoria: 'I', espacos: 1,
    desc: 'Instalar: ação completa e Tática DT 15 (se falhar, gasta a mina). Detonar: ação padrão a até alcance longo.\nCone de 6 m, 12d6 de perfuração (Reflexos DT Int reduz à metade). Encontrar: Percepção (DT = seu teste de instalação). Categoria I, 1 espaço.' },

  /* ===== ITENS OPERACIONAIS ===== */
  { nome: 'Algemas', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: 'Para prender quem não está indefeso: empunhar, agarrar e vencer outro teste de agarrar. Prende os dois pulsos (–5 em testes com as mãos, impede conjuração) ou um pulso a um objeto imóvel. Escapar: Acrobacia DT 30 (ou ter a chave). Categoria 0, 1 espaço.' },
  { nome: 'Arpéu', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: 'Gancho para amarrar na ponta de uma corda. Prender: Pontaria DT 15. Subir um muro com corda: +5 em Atletismo. Categoria 0, 1 espaço.' },
  { nome: 'Bandoleira', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Cinto com bolsos e alças. Uma vez por rodada, sacar ou guardar um item do inventário como ação livre. Categoria I, 1 espaço.' },
  { nome: 'Binóculos', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: 'Binóculos militares: +5 em testes de Percepção para observar coisas distantes. Categoria 0, 1 espaço.' },
  { nome: 'Bloqueador de Sinal', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Emite interferência: nenhum celular em alcance médio consegue se conectar. Categoria I, 1 espaço.' },
  { nome: 'Cicatrizante', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Spray. Ação padrão: gasta este item e cura 2d8+2 PV em você ou em um ser adjacente. Categoria I, 1 espaço.' },
  { nome: 'Corda', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: 'Rolo de 10 m. +5 em Atletismo para descer buracos/prédios; amarrar inconscientes etc. Categoria 0, 1 espaço.' },
  { nome: 'Equipamento de Sobrevivência', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 2,
    desc: 'Saco de dormir, panelas, GPS e afins. +5 em Sobrevivência para acampar e orientar-se, e permite esses testes sem treinamento. Categoria 0, 2 espaços.' },
  { nome: 'Lanterna Tática', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Ilumina um cone de 9 m. Ação de movimento: mirar nos olhos de um ser em alcance curto — ele fica ofuscado por 1 rodada, mas imune à lanterna pelo resto da cena. Categoria I, 1 espaço.' },
  { nome: 'Máscara de Gás', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: '+10 em testes de Fortitude contra efeitos que dependam de respiração. Categoria 0, 1 espaço.' },
  { nome: 'Mochila Militar', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 0,
    desc: 'Não ocupa espaço e aumenta a capacidade de carga em +2 espaços. Categoria I.' },
  { nome: 'Óculos de Visão Térmica', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Eliminam a penalidade em testes por camuflagem. Categoria I, 1 espaço.' },
  { nome: 'Pé de Cabra', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: '+5 em testes de Força para arrombar portas. Em combate, funciona como um bastão. Categoria 0, 1 espaço.' },
  { nome: 'Pistola de Dardos', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1, dano: '—', alcance: 'Curto', pericia: 'Pontaria',
    desc: 'Arma leve, alcance curto. Se acertar, o alvo fica inconsciente até o fim da cena (Fortitude DT Agi reduz para desprevenido e lento por 1 rodada). Vem com 2 dardos. Categoria I, 1 espaço.' },
  { nome: 'Pistola Sinalizadora', tipo: 'arma', grupo: 'Itens Operacionais', categoria: '0', espacos: 1, dano: '2d6', critico: 20, multiplicador: 2, alcance: 'Curto', tipoDano: 'Fogo', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Dispara um sinalizador. Pode ser usada como arma de disparo leve: 2d6 de fogo, alcance curto. Vem com 2 cargas. Categoria 0, 1 espaço.' },
  { nome: 'Soqueira', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: '+1 no dano desarmado e torna esse dano letal. Pode receber modificações e maldições de armas corpo a corpo, aplicadas nos ataques desarmados. Categoria 0, 1 espaço.' },
  { nome: 'Spray de Pimenta', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Ação padrão, ser adjacente: fica cego por 1d4 rodadas (Fortitude DT Agi evita). Dois usos. Categoria I, 1 espaço.' },
  { nome: 'Taser', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Ação padrão, ser adjacente: 1d6 de eletricidade e atordoado por 1 rodada (Fortitude DT Agi evita). Dois usos. Categoria I, 1 espaço.' },
  { nome: 'Traje Hazmat', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 2,
    desc: 'Cobre o corpo inteiro. +5 em testes de resistência contra efeitos ambientais e resistência a químico 10. Categoria I, 2 espaços.' },

  /* ===== ITENS PARANORMAIS / AMALDIÇOADOS ===== */
  { nome: 'Amarras de Sangue', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Cordas/correntes do elemento Sangue, para imobilizar criaturas vulneráveis a Sangue.\nArmadilha: gasta as amarras, ação completa e 2 PE — área 3x3 m. Criatura que entre (1ª vez no turno) faz Reflexos (DT Int); falha = imóvel até o fim da cena; sucesso = terreno difícil.\nLaçar: ação padrão e 1 PE, criatura em alcance curto. Vontade (DT Agi) ou paralisada até o início do próximo turno (pode repetir). Manter: 1 PE por rodada.' },
  { nome: 'Amarras de Morte', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Como Amarras de Sangue, mas do elemento Morte (imobiliza criaturas vulneráveis a Morte).\nArmadilha: ação completa + 2 PE. Laçar: ação padrão + 1 PE, manter 1 PE/rodada.' },
  { nome: 'Amarras de Energia', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Como Amarras de Sangue, mas do elemento Energia.\nArmadilha: ação completa + 2 PE. Laçar: ação padrão + 1 PE, manter 1 PE/rodada.' },
  { nome: 'Amarras de Conhecimento', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Como Amarras de Sangue, mas do elemento Conhecimento.\nArmadilha: ação completa + 2 PE. Laçar: ação padrão + 1 PE, manter 1 PE/rodada.' },
  { nome: 'Câmera de Aura Paranormal', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'II', espacos: 1,
    desc: 'Câmera amaldiçoada com Energia e sigilos de Conhecimento. Tirar foto: ação padrão e 1 PE. Revela auras paranormais em pessoas e objetos, na cor do elemento.' },
  { nome: 'Componentes Ritualísticos de Energia', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'I', espacos: 1,
    desc: 'Necessários para conjurar rituais de Energia: eletricidade, dispositivos, circuitos, fontes de calor/luz, pilhas, cabos, pólvora, ímãs… Categoria I, 1 espaço.' },
  { nome: 'Componentes Ritualísticos de Sangue', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'I', espacos: 1,
    desc: 'Necessários para conjurar rituais de Sangue: órgãos, carne, sangue, animais (sacrifício), navalhas, agulhas, arame farpado, correntes, metal enferrujado… Categoria I, 1 espaço.' },
  { nome: 'Componentes Ritualísticos de Morte', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'I', espacos: 1,
    desc: 'Necessários para conjurar rituais de Morte: ossos, dentes, cinzas, cabelo, cristais pretos, relógios, galhos secos, areia, poeira, lodo… Categoria I, 1 espaço.' },
  { nome: 'Componentes Ritualísticos de Conhecimento', tipo: 'amaldicoado', grupo: 'Itens Paranormais', categoria: 'I', espacos: 1,
    desc: 'Necessários para conjurar rituais de Conhecimento. Não existem componentes de Medo. Categoria I, 1 espaço.' }
];
