/* Catálogo oficial de equipamentos — Ordem Paranormal RPG 1ª edição */
const ITENS_CATALOG = [
  /* ===== ARMAS SIMPLES ===== */
  { nome: 'Coronhada', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 0, dano: '1d4/1d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Golpe com a coronha da arma de fogo. 1d4 (uma mão) ou 1d6 (duas mãos), crítico x2, impacto. Não ocupa espaço próprio.' },
  { nome: 'Faca', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d4', critico: 19, multiplicador: 2, alcance: 'Curto', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Lâmina afiada (navalha, faca militar ou de churrasco). Arma ágil (usa Agilidade) e pode ser arremessada (alcance curto). Dano 1d4, crítico 19, corte, 1 espaço, categoria 0.' },
  { nome: 'Martelo', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Martelo comum de ferramenta. Dano 1d6, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Punhal', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d4', critico: 20, multiplicador: 3, alcance: '—', tipoDano: 'Perfurante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Adaga ou punhal. Arma ágil (usa Agilidade). Dano 1d4, crítico x3, perfuração, 1 espaço, categoria 0.' },
  { nome: 'Bastão', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6/1d8', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Cilindro de madeira (cassetete, taco, tonfa). Uma mão 1d6 ou duas mãos 1d8, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Machete', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Lâmina longa e larga. Dano 1d6, crítico 19, corte, 1 espaço, categoria 0.' },
  { nome: 'Lança', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 1, dano: '1d6', critico: 20, multiplicador: 2, alcance: 'Curto', tipoDano: 'Perfurante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Haste com ponta metálica. Pode ser arremessada (alcance curto). Dano 1d6, crítico x2, perfuração, 1 espaço, categoria 0.' },
  { nome: 'Cajado', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 2, dano: '1d6/1d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Cabo de madeira ou barra longa. Arma ágil (usa Agilidade); pode ser usada com Combater com Duas Armas. Dano 1d6/1d6, crítico x2, impacto, 2 espaços, categoria 0.' },
  { nome: 'Arco', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 2, dano: '1d6', critico: 20, multiplicador: 3, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arco simples. Consome flechas. Dano 1d6, crítico x3, alcance médio, perfuração, 2 espaços, categoria 0.' },
  { nome: 'Besta', tipo: 'arma', grupo: 'Armas Simples', categoria: '0', espacos: 2, dano: '1d8', critico: 19, multiplicador: 2, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Besta de mão. Recarregar gasta ação de movimento a cada disparo. Consome flechas. Dano 1d8, crítico 19, alcance médio, perfuração, 2 espaços, categoria 0.' },
  { nome: 'Pistola', tipo: 'arma', grupo: 'Armas Simples', categoria: 'I', espacos: 1, dano: '1d12', critico: 18, multiplicador: 2, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma de fogo curta. Consome balas curtas. Dano 1d12, crítico 18, alcance curto, balístico, 1 espaço, categoria I.' },
  { nome: 'Revólver', tipo: 'arma', grupo: 'Armas Simples', categoria: 'I', espacos: 1, dano: '2d6', critico: 19, multiplicador: 3, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma de fogo de tambor. Consome balas curtas. Dano 2d6, crítico 19/x3, alcance curto, balístico, 1 espaço, categoria I.' },
  { nome: 'Fuzil de Caça', tipo: 'arma', grupo: 'Armas Simples', categoria: 'I', espacos: 2, dano: '2d8', critico: 19, multiplicador: 3, alcance: 'Médio', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Fuzil civil. Consome balas longas. Dano 2d8, crítico 19/x3, alcance médio, balístico, 2 espaços, categoria I.' },

  /* ===== ARMAS TÁTICAS ===== */
  { nome: 'Machadinha', tipo: 'arma', grupo: 'Armas Táticas', categoria: '0', espacos: 1, dano: '1d6', critico: 20, multiplicador: 3, alcance: 'Curto', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Machado pequeno. Pode ser arremessada (alcance curto). Dano 1d6, crítico x3, corte, 1 espaço, categoria 0.' },
  { nome: 'Nunchaku', tipo: 'arma', grupo: 'Armas Táticas', categoria: '0', espacos: 1, dano: '1d8', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Arma ágil (usa Agilidade). Dano 1d8, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Corrente', tipo: 'arma', grupo: 'Armas Táticas', categoria: '0', espacos: 1, dano: '1d8', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: '+2 em testes de desarmar/derrubar. Dano 1d8, crítico x2, impacto, 1 espaço, categoria 0.' },
  { nome: 'Espada', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '1d8/1d10', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Uma mão 1d8 ou duas mãos 1d10, crítico 19, corte, 1 espaço, categoria I.' },
  { nome: 'Florete', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '1d6', critico: 18, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Arma ágil (usa Agilidade). Dano 1d6, crítico 18, corte, 1 espaço, categoria I.' },
  { nome: 'Machado', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '1d8', critico: 20, multiplicador: 3, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 1d8, crítico x3, corte, 1 espaço, categoria I.' },
  { nome: 'Maça', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '2d4', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 2d4, crítico x2, impacto, 1 espaço, categoria I.' },
  { nome: 'Acha', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d12', critico: 20, multiplicador: 3, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 1d12, crítico x3, corte, 2 espaços, categoria I.' },
  { nome: 'Gadanho', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '2d4', critico: 20, multiplicador: 4, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 2d4, crítico x4, corte, 2 espaços, categoria I.' },
  { nome: 'Katana', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d10', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Arma ágil se você for veterano em Luta. Dano 1d10, crítico 19, corte, 2 espaços, categoria I.' },
  { nome: 'Marreta', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '3d4', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Impacto', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 3d4, crítico x2, impacto, 2 espaços, categoria I.' },
  { nome: 'Montante', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '2d6', critico: 19, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Dano 2d6, crítico 19, corte, 2 espaços, categoria I.' },
  { nome: 'Motosserra', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '3d6', critico: 20, multiplicador: 2, alcance: '—', tipoDano: 'Cortante', pericia: 'Luta', atributoDano: 'Força',
    desc: 'Rolar 6 num dado de dano soma um dado extra; –O no ataque; ligar gasta ação de movimento. Dano 3d6, crítico x2, corte, 2 espaços, categoria I.' },
  { nome: 'Arco Composto', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d10', critico: 20, multiplicador: 3, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Força',
    desc: 'Aplica Força no dano (diferente de outras armas de disparo). Consome flechas. Dano 1d10, crítico x3, alcance médio, 2 espaços, categoria I.' },
  { nome: 'Balestra', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '1d12', critico: 19, multiplicador: 2, alcance: 'Médio', tipoDano: 'Perfurante', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Recarregar gasta ação de movimento a cada disparo. Consome flechas. Dano 1d12, crítico 19, alcance médio, 2 espaços, categoria I.' },
  { nome: 'Submetralhadora', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 1, dano: '2d6', critico: 19, multiplicador: 3, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma automática: rajada dá –O no ataque mas +1 dado de dano do mesmo tipo. Consome balas curtas. Dano 2d6, crítico 19/x3, alcance curto, 1 espaço, categoria I.' },
  { nome: 'Espingarda', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'I', espacos: 2, dano: '4d6', critico: 20, multiplicador: 3, alcance: 'Curto', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Metade do dano em alcance médio ou maior. Consome cartuchos. Dano 4d6, crítico x3, alcance curto, 2 espaços, categoria I.' },
  { nome: 'Fuzil de Assalto', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'II', espacos: 2, dano: '2d10', critico: 19, multiplicador: 3, alcance: 'Médio', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Arma automática: rajada dá –O no ataque mas +1 dado de dano. Consome balas longas. Dano 2d10, crítico 19/x3, alcance médio, 2 espaços, categoria II.' },
  { nome: 'Fuzil de Precisão', tipo: 'arma', grupo: 'Armas Táticas', categoria: 'III', espacos: 2, dano: '2d10', critico: 19, multiplicador: 3, alcance: 'Longo', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Se veterano em Pontaria e mirar com ele, +5 na margem de ameaça. Consome balas longas. Dano 2d10, crítico 19/x3, alcance longo, 2 espaços, categoria III.' },

  /* ===== ARMAS PESADAS ===== */
  { nome: 'Bazuca', tipo: 'arma', grupo: 'Armas Pesadas', categoria: 'III', espacos: 2, dano: '10d8', critico: 20, multiplicador: 2, alcance: 'Médio', tipoDano: 'Impacto', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Atinge o alvo + todos num raio de 3 m (Reflexos DT Agi reduz à metade, exceto o alvo direto); pode disparar num ponto vazio (sem teste de ataque); recarregar gasta ação de movimento. Consome foguete. Dano 10d8, crítico x2, 2 espaços, categoria III.' },
  { nome: 'Lança-chamas', tipo: 'arma', grupo: 'Armas Pesadas', categoria: 'III', espacos: 2, dano: '6d6', critico: 20, multiplicador: 2, alcance: 'Curto', tipoDano: 'Fogo', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Atinge todos numa linha de 1,5 m de largura a alcance curto (1 teste de ataque vs Defesa de todos); atingidos também ficam em chamas. Consome combustível. Dano 6d6 fogo, crítico x2, 2 espaços, categoria III.' },
  { nome: 'Metralhadora', tipo: 'arma', grupo: 'Armas Pesadas', categoria: 'II', espacos: 2, dano: '2d12', critico: 19, multiplicador: 3, alcance: 'Médio', tipoDano: 'Balístico', pericia: 'Pontaria', atributoDano: 'Agilidade',
    desc: 'Precisa Força 4+ ou ação de movimento para apoiar em tripé, senão –5 no ataque; é automática (rajada: –O no ataque, +1 dado de dano). Consome balas longas. Dano 2d12, crítico 19/x3, alcance médio, 2 espaços, categoria II.' },

  /* ===== MUNIÇÃO ===== */
  { nome: 'Flechas', tipo: 'municao', grupo: 'Munição', categoria: '0', espacos: 1,
    desc: 'Pacote de flechas/virotes. Duração: 1 missão inteira. 1 espaço, categoria 0.' },
  { nome: 'Balas Curtas', tipo: 'municao', grupo: 'Munição', categoria: '0', espacos: 1,
    desc: 'Munição para pistola, revólver e submetralhadora. Duração do pacote: 2 cenas. 1 espaço, categoria 0.' },
  { nome: 'Balas Longas', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Munição para fuzis e metralhadora. Duração do pacote: 1 cena. 1 espaço, categoria I.' },
  { nome: 'Cartuchos', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Munição para espingarda. Duração do pacote: 1 cena. 1 espaço, categoria I.' },
  { nome: 'Combustível', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Para lança-chamas. Duração do pacote: 1 cena. 1 espaço, categoria I.' },
  { nome: 'Foguete', tipo: 'municao', grupo: 'Munição', categoria: 'I', espacos: 1,
    desc: 'Para bazuca. Duração: 1 disparo. 1 espaço, categoria I.' },

  /* ===== PROTEÇÕES ===== */
  { nome: 'Proteção Leve', tipo: 'protecao', grupo: 'Proteções', categoria: 'I', espacos: 2, defesa: 5,
    desc: 'Defesa +5, categoria I, 2 espaços. Sem proficiência: –OO em testes baseados em Força e Agilidade.' },
  { nome: 'Proteção Pesada', tipo: 'protecao', grupo: 'Proteções', categoria: 'II', espacos: 5, defesa: 10,
    desc: 'Defesa +10, categoria II, 5 espaços. RD 2 contra balístico/corte/impacto/perfuração; –5 em perícias com penalidade de carga. Sem proficiência: –OO em testes de Força e Agilidade.' },
  { nome: 'Escudo', tipo: 'protecao', grupo: 'Proteções', categoria: 'I', espacos: 2, defesa: 2,
    desc: 'Defesa +2, categoria I, 2 espaços. Precisa ser empunhado numa mão; soma com a Defesa de outra proteção; conta como pesada para fins de proficiência.' },

  /* ===== EQUIPAMENTO GERAL ===== */
  { nome: 'Kit de Perícia', tipo: 'geral', grupo: 'Acessórios', categoria: '0', espacos: 1,
    desc: 'Categoria 0, 1 espaço. Necessário para certas perícias/usos (sem ele: –5 no teste).' },
  { nome: 'Mochila Militar', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 0,
    desc: 'Categoria I. Não ocupa espaço; +2 espaços de carga.' },
  { nome: 'Cicatrizante', tipo: 'geral', grupo: 'Itens Operacionais', categoria: 'I', espacos: 1,
    desc: 'Categoria I, 1 espaço. Ação padrão cura 2d8+2 PV em si ou adjacente.' },
  { nome: 'Algemas', tipo: 'geral', grupo: 'Itens Operacionais', categoria: '0', espacos: 1,
    desc: 'Categoria 0, 1 espaço. Prende alguém não indefeso (empunhar + agarrar + vencer novo teste de agarrar); –5 em ações com as mãos, impede conjurar; escapar exige Acrobacia DT 30.' },
  { nome: 'Granada de Atordoamento', tipo: 'geral', grupo: 'Explosivos', categoria: '0', espacos: 1,
    desc: 'Categoria 0, 1 espaço. Raio 6 m: atordoado 1 rodada (Fortitude DT Agi reduz para ofuscado+surdo 1 rodada). Arremessar: empunhar + ação padrão, alcance médio.' },
  { nome: 'Granada de Fragmentação', tipo: 'geral', grupo: 'Explosivos', categoria: 'I', espacos: 1,
    desc: 'Categoria I, 1 espaço. Raio 6 m: 8d6 perfuração (Reflexos DT Agi reduz à metade).' },
  { nome: 'Granada de Fumaça', tipo: 'geral', grupo: 'Explosivos', categoria: '0', espacos: 1,
    desc: 'Categoria 0, 1 espaço. Raio 6 m: cego + camuflagem total por 2 rodadas.' },
  { nome: 'Granada Incendiária', tipo: 'geral', grupo: 'Explosivos', categoria: 'I', espacos: 1,
    desc: 'Categoria I, 1 espaço. Raio 6 m: 6d6 fogo + em chamas (Reflexos DT Agi reduz dano à metade e evita a condição).' }
];

if (typeof window !== 'undefined') window.ITENS_CATALOG = ITENS_CATALOG;
